### ISSUE TITLE
404 error when generating stack report

### ISSUE THREAD

**Issue by sivaavkd** [fabric8-analytics/fabric8-analytics-vscode-extension#116]
I updated my extensions using the latest vsix files (fabric8-analytics-0.0.19.vsix and osio-auth-service-0.0.17.vsix)... I was able to generate Stack Report.. 

But, I found an issue after that.  saw that there is an update for VSCode in the settings icon (bottom left corner).. I clicked on "Reload to update".. Then, VSCode editor reloaded and Stack report is not coming up now. It is showing an error, "Failed to trigger stack analysis, Status:404"

after reload of VSCode, it is now "Version 1.19.3"

**Comment by invincibleJai** [comment]
@siva issue has been fixed
