### ISSUE TITLE
Error handling in VSCode extension

### ISSUE THREAD

**Issue by sivaavkd** [fabric8-analytics/fabric8-analytics-vscode-extension#117]
When I found the issue mentioned #116 , I also saw that error was not handled properly.  The status bar in the bottom of the VSCode window is showing "Analyzing your stack ..." continuously.  Shouldn't it time out after sometime ?  It is still showing up even after I close the stack report tab.

**Comment by invincibleJai** [comment]
It's been fixed @sivaavkd
