### ISSUE TITLE
Command fails if no editors are open

### ISSUE THREAD

**Issue by gorkem** [fabric8-analytics/fabric8-analytics-vscode-extension#128]
Invoking `generate application stack report` when no editors are open fails with the following error.
I used the command palette (F1) to invoke the command.
`Running the contributed command:'extension.fabric8AnalyticsWidget' failed.`

**Comment by invincibleJai** [comment]
This PR should fix it https://github.com/fabric8-analytics/fabric8-analytics-vscode-extension/pull/129/files
