### ISSUE TITLE
400 error on triggering stack analysis

### ISSUE THREAD

**Issue by rootAvish** [fabric8-analytics/fabric8-analytics-vscode-extension#142]
"Generate stack report on manifest" gives 400 error for twitter-core folder, works for workspace but with default maven, analyses dependencies are reported as 0.

Repository: https://github.com/yusuke/twitter4j 
tried with https://github.com/yusuke/twitter4j/tree/master/twitter4j-core 

/cc @sara-02 You might want to add additional info here.

**Comment by sara-02** [comment]
As we observed, the objects are all empty, the generating pom path is not giving any error, infact when run locally the effective pom is getting successfully build, but after then when the stack analysis is called, the objects are not allocated the correct values, leading to the `Manifest file not correct 400 error`

**Comment by invincibleJai** [comment]
@sara-02 I tried with latest version , it works for me i.e Stack analysis for workspace as well as individual manifest's were working fine. 

I'll request to try again with proper VSIX cc @samuzzal-choudhury @rootAvish

**Comment by ravsa** [comment]
@invincibleJai I tried with 
`vscode [ 1.25.1 ]`
```bash
LSB Version:	:core-4.1-amd64:core-4.1-noarch
Distributor ID:	Fedora
Description:	Fedora release 28 (Twenty Eight)
Release:	28
Codename:	TwentyEight
```  still facing the issue.

**Comment by invincibleJai** [comment]
fixed with https://github.com/fabric8-analytics/fabric8-analytics-vscode-extension/pull/149

Thanks :)

**Comment by samuzzal-choudhury** [comment]
This issue was moved to openshiftio/openshift.io#4252
