### ISSUE TITLE
"Not correct pom" error in effective pom generation

### ISSUE THREAD

**Issue by rootAvish** [fabric8-analytics/fabric8-analytics-vscode-extension#143]
For the repository: https://github.com/alibaba/Sentinel

/cc @sara-02

**Comment by sara-02** [comment]
This could be an error with the pom itself. Because the effective generation did not build locally for me, if one of you can verify that the effective pom is failing, then we can close this issue.

**Comment by invincibleJai** [comment]
Fixed, can be verified in the latest release.
