### ISSUE TITLE
Effective POM generation taking too long

### ISSUE THREAD

**Issue by rootAvish** [fabric8-analytics/fabric8-analytics-vscode-extension#144]
For the repository:https://github.com/fabric8-analytics/fabric8-analytics-devstudio-plugin, effective pom generation took well over five-ten minutes. Can be a possible bandwidth issue.

/cc @GeetikaBatra Might want to add more details here.

**Comment by invincibleJai** [comment]
@GeetikaBatra did it worked for you? taking long for first time can be observed as dependencies won't be there in m2 so it'll download all.

**Comment by invincibleJai** [comment]
Tried on workSpace got `Error: MaxBuffer Exceeded` than pulled dependencies locally with `mvn install` post this it worked. Above command took more than 7 mins for me.

![screen shot 2018-08-27 at 3 06 27 pm](https://user-images.githubusercontent.com/5129024/44653214-bbfbbe80-aa0b-11e8-8a61-885cadad3aac.png)


Below is screenshot post stack-analysis : 

![screen shot 2018-08-27 at 3 11 02 pm](https://user-images.githubusercontent.com/5129024/44653251-d897f680-aa0b-11e8-89c9-3f510783383f.png)
