### ISSUE TITLE
For NPM ecosystem, triggering stack analysis either on workspace or on manifest file results in "Failed to resolve dependencies error"

### ISSUE THREAD

**Issue by rootAvish** [fabric8-analytics/fabric8-analytics-vscode-extension#145]
Tried with the repositories:

https://github.com/sindresorhus/refined-twitter
https://github.com/chalk/chalk

Tried triggering stack analysis through both the workspace and manifest option, but both times it failed to generate package.json in "target" folder with the message:
"Failed to resolve dependencies". VSCode version was 1.26.0.

/cc @ravsa I think he faced the same issue.

**Comment by invincibleJai** [comment]
@rootAvish tried with chalk and it worked as expected. Pls try in debug mode if you get time.

@ravsa did you as well faced similar issue?

**Comment by invincibleJai** [comment]
Same issue was observed by @sivaavkd as well. Below are the details : 

node -v
v9.4.0
npm -v
5.6.0
VSCode Version 1.26.1 (1.26.1)
MacOsx

**Comment by rootAvish** [comment]
@invincibleJai Please see the console output of running the extension in debug mode: https://gist.github.com/rootAvish/9edee79d3cece3a4a29cb3fbf7c20184 It is able to run npm install however it's infinite looping and trying to run the same over and again.

**Comment by rootAvish** [comment]
Working for me with a reinstall of NPM, node and running `npm cache clean --force`. If the issue elsewhere is also due to problems with NPM, I'll close the same.

**Comment by samuzzal-choudhury** [comment]
This is not an issue anymore. Hence, closing.

**Comment by samuzzal-choudhury** [comment]
This issue was moved to openshiftio/openshift.io#4253
