### ISSUE TITLE
Not all dependencies sent for analysis when triggering stack analysis for NPM

### ISSUE THREAD

**Issue by rootAvish** [fabric8-analytics/fabric8-analytics-vscode-extension#146]
1. stack report generatation for NPM shows effective pom specific log on the IDE
2. NPM package @angular/core ^6.1.0 was not version resolved properly and hence was not displayde as an unknown component in the stack report. (PeerDependencies were set as Dependencies for testing)

/cc @samuzzal-choudhury

**Comment by invincibleJai** [comment]
Closing it as `npm list` doesn't resolve absolute version for @angular/core as it have UNMET PEER DEPENDENCIES FOR other dependencies used in manifest i.e pkg A needs @angular/core > 4.0.0 but there could be a pkg B which need @angular/core <3.0.0

CC @samuzzal-choudhury

**Comment by samuzzal-choudhury** [comment]
This issue was moved to openshiftio/openshift.io#4254
