### ISSUE TITLE
Infinite Looping error with user's npm

### ISSUE THREAD

**Issue by sara-02** [fabric8-analytics/fabric8-analytics-vscode-extension#150]
My node was properly installed, but there was some error with ppm, even `npm -v` was not correctly working.
When I generated the stack report for a package.json, the process of generating effective pom went into an infinite loop of failure, instead of existing after the first try with a message.
After fixing my npm, the report worked as expected

VScode: 1.26.1
OS: Fedora
Packag.json: yarn
https://github.com/yarnpkg/yarn
![screenshot from 2018-08-23 12-19-57](https://user-images.githubusercontent.com/7047079/44510420-42459700-a6d2-11e8-9978-5aa3a497705e.png)
![screenshot from 2018-08-23 12-16-51](https://user-images.githubusercontent.com/7047079/44510421-42459700-a6d2-11e8-9964-f26085134c0a.png)

**Comment by rootAvish** [comment]
Resolution is to not try to rerun npm install when stderr is present.

**Comment by sara-02** [comment]
While for whole workspace there is an error in the developer log, for the single manifest there is no developer log and no action is taken. When the camelcase is changed, it worked.
We should take some action, to generate the appropriate error, and bring it to the foreground. Because it looks as if the extension stopped working, even though that is not the case. 
cc @invincibleJai

**Comment by invincibleJai** [comment]
@sara-02 yes it's true, current fix will avoid loop and it will show user with Stdout error.

**Comment by samuzzal-choudhury** [comment]
This issue was moved to openshiftio/openshift.io#4248
