### ISSUE TITLE
Analysis stuck on "generating application stack report"

### ISSUE THREAD

**Issue by rootAvish** [fabric8-analytics/fabric8-analytics-vscode-extension#154]
For the repository: https://github.com/codecentric/spring-boot-admin

Reported by @ravsa @sunilk747

**Comment by invincibleJai** [comment]
The challenge here with `trigger stack analysis at workspace level` as above repo has both `pom.xml` and `package.json` which we don't support multiple ecosystems as of now. 

To start with an ideal approach would be to check for root level pom, if any consider it as maven project and proceed.

NOTE: User can still trigger stack analysis on particular manifest file be it pom.xml, package.json.

cc @samuzzal-choudhury @miteshvp any inputs/suggestions.

**Comment by invincibleJai** [comment]
Sure @miteshvp I agree we need to support `package.json` as well in this scenario we'll discuss it and take it as the enhancement. For time  I feel we can have my approach.

**Comment by samuzzal-choudhury** [comment]
This issue was moved to openshiftio/openshift.io#4251
