### ISSUE TITLE
Getting stack report for only two manifests when running stack analysis, multiple effective POM files are present in target folder

### ISSUE THREAD

**Issue by rootAvish** [fabric8-analytics/fabric8-analytics-vscode-extension#155]
For the repository: https://github.com/apache/maven

I have the following structure in the target folder:

```
.
└── stackinfo
    └── poms
        ├── apache-maven
        │   └── pom.xml
        ├── maven-artifact
        │   └── pom.xml
        ├── maven-builder-support
        │   └── pom.xml
        ├── maven-compat
        │   └── pom.xml
        ├── maven-core
        │   ├── pom.xml
        │   └── target
        │       └── pom.xml
        ├── maven-embedder
        │   └── pom.xml
        ├── maven-model
        │   └── pom.xml
        ├── maven-model-builder
        │   └── pom.xml
        ├── maven-plugin-api
        │   └── pom.xml
        ├── maven-repository-metadata
        │   └── pom.xml
        ├── maven-resolver-provider
        │   └── pom.xml
        ├── maven-settings
        │   └── pom.xml
        ├── maven-settings-builder
        │   └── pom.xml
        ├── maven-slf4j-provider
        │   └── pom.xml
        └── pom.xml
```

Screenshot of the problem:
![screen shot 2018-08-24 at 12 23 46 pm](https://user-images.githubusercontent.com/5445560/44569639-afbbfb00-a798-11e8-9270-4b3f700a320b.png)

**Comment by invincibleJai** [comment]
@rootAvish I tried now twice on same repo, looks good to me. Did i miss something?

<img width="1422" alt="screen shot 2018-08-24 at 12 48 13 pm" src="https://user-images.githubusercontent.com/5129024/44570882-e562e300-a79c-11e8-9e3a-ed17325f42da.png">

**Comment by rootAvish** [comment]
@invincibleJai I tried it again after deleting target folder, still same result. Maybe you can see this issue on my laptop on Monday.

/cc @samuzzal-choudhury I had pinged you the stack-id for this the other day, did you get a chance to check if two stack analyses were triggered or more?

**Comment by sivaavkd** [comment]
@rootAvish is this still an issue? if not, can we close this ?

**Comment by rootAvish** [comment]
This is no longer an issue.
