### ISSUE TITLE
Generate application stack report for manifest file is throwing unable to parse error for package.json

### ISSUE THREAD

**Issue by avkkiran** [fabric8-analytics/fabric8-analytics-vscode-extension#216]
Steps to reproduce the issue:

1. In my Ubuntu 16.0.4 Oracle Virtual Machine, I opened my package.json file which is at /Downloads/btm/npm-modules/btm-ui/ path.
2. I right-clicked on the file and clicked on "Generate application stack report for manifest file" and it caused to throw Unable to parse error which can be seen in the attached screenshot.

Also if I right-click on the file and select "Generate application stack report for workspace", then also it is causing Unable to parse error with a slightly different error message.

![package json_workspace_error](https://user-images.githubusercontent.com/25317184/47547251-6ad85000-d912-11e8-9f6d-65df0ffc00e7.png)
![package json_manifest_error](https://user-images.githubusercontent.com/25317184/47547252-6b70e680-d912-11e8-940a-bb9d26b7c6c8.png)

**Comment by invincibleJai** [comment]
thanks, @avkkiran for trying out the extension and helping us improve with logging the issue. We'll look into it.

**Comment by invincibleJai** [comment]
@avkkiran please try with latest release of extension 0.10.0. If you still face issues pls share logs, can be seen at `Help-> toggle developer tool`

**Comment by sivaavkd** [comment]
@avkkiran can you please help with this ? cc @invincibleJai

**Comment by invincibleJai** [comment]
Thanks @kpiwko for the info, will look into it.

**Comment by invincibleJai** [comment]
Closing as fixed. Feel free to reopen if not.
