### ISSUE TITLE
Generate application stack report for workspace is throwing unable to parse error for pom.xml

### ISSUE THREAD

**Issue by avkkiran** [fabric8-analytics/fabric8-analytics-vscode-extension#217]
Steps to reproduce the issue:

In my Ubuntu 16.0.4 Oracle Virtual Machine, I opened my pom.xml file which is at /Downloads/btm/api/pom.xml path.

I right-clicked on the file and clicked on "Generate application stack report for workspace" and it caused to throw Unable to parse error which can be seen in the attached screenshot.
However if I select "Generate application stack report for manifest file", it is working fine.

![pom xml_workspace_error](https://user-images.githubusercontent.com/25317184/47547458-25685280-d913-11e8-9be9-51204db918a9.png)

**Comment by invincibleJai** [comment]
thanks, @avkkiran for trying out the extension and helping us improve with logging the issue. We'll look into it.

**Comment by invincibleJai** [comment]
@avkkiran please try with the latest release of extension 0.10.0. If you still face issues pls share logs, can be seen at `Help-> toggle developer tool`

**Comment by sivaavkd** [comment]
@avkkiran can you please help with this ? cc @invincibleJai

**Comment by invincibleJai** [comment]
Closing it as unable to replicate this behavior with the latest release.
