### ISSUE TITLE
Support multi-project workspace without root project

### ISSUE THREAD

**Issue by apupier** [fabric8-analytics/fabric8-analytics-vscode-extension#225]
I have two projects in same folder that i open with VS Code. When I right-click on a pom.xml -> Generate application stack report on workspace I have a dialog message saying: "Coudn't find manifest at root workspace level"

**Comment by invincibleJai** [comment]
Thanks, it's a WIP feature. We'll be supporting it soon

https://github.com/openshiftio/openshift.io/issues/4496

**Comment by invincibleJai** [comment]
Changes are in mater, closing it.
