### ISSUE TITLE
Reference to Openshift.io in generated report in VS Code

### ISSUE THREAD

**Issue by apupier** [fabric8-analytics/fabric8-analytics-vscode-extension#226]
![image](https://user-images.githubusercontent.com/1105127/47718966-0d157200-dc4a-11e8-8daf-f92aa63c4d98.png)

Users are installing a "Dependency Analytics" created by red Hat with if name redhat.fabric8-analytics inside VS Code. they can have no clue what OpenShift.io is

by the way there is a typo, it is OpenShift.io and not Openshift.io

**Comment by invincibleJai** [comment]
thanks, @apupier for filing this.

**Comment by invincibleJai** [comment]
All references of "OpenShift.io Analytics" would be replaced with "Dependency Analytics".

**Comment by invincibleJai** [comment]
Changes are in prod, hence closing.
