### ISSUE TITLE
Irritating "Scanned  dependencies" Pop-up every time a pom.xml opens

### ISSUE THREAD

**Issue by fbricon** [fabric8-analytics/fabric8-analytics-vscode-extension#239]
This is super annoying, since it happens even though no changes were made to the pom. There should be a way to silence it definitely  (don't show again). Also, it's inconsistent: it shows up when the pom.xml opens, but not when you add a new dependency to that pom.

Anyways, it should not get in the way. Ideally it should opens only when something wrong is detected. Other times, a simple update of the status bar to indicate a scan is performed should be enough.

You should strive to stay non-intrusive.

**Comment by invincibleJai** [comment]
thanks @fbricon for input. It's a valid suggestion. The intention here was to let user know that scan has happened in the background and can trigger "Dependency Analytics Report". Currently, we are showing only on file open(`pom.xml/package.json`) and not on edits to avoid these popups.

Can we have the popup shown only once for a user if user open's a manifest file first time. Next time onwards show only if any CVEs are detected else no. 

cc @miteshvp 

@fbricon @SriKrishnaPaparaju let me know your thoughts.

**Comment by invincibleJai** [comment]
It can be closed as currently, we show info message 1st time when a manifest file is opened & whenever the scan detects a security vulnerability.

**Comment by fbricon** [comment]
popup stills shows up every time I reopen vscode. This is getting old very quickly

**Comment by invincibleJai** [comment]
@fbricon yes currently it shows up every time once you open code and opens manifest file (irrespective of CVEs are present or not) unlike earlier when Pop-up shows up every time a pom.xml opens.

So your proposal is to show only if CVEs are present on code/file open? 

cc @SriKrishnaPaparaju
