### ISSUE TITLE
CMD+D for dependencies analysis vs CMD+D for "select next occurrence of selection"

### ISSUE THREAD

**Issue by williamcaban** [fabric8-analytics/fabric8-analytics-vscode-extension#252]
When using this plugin in Mac it creates the Keybinding of CMD+D for dependencies analysis but CMD+D is also default in VSCode for selecting the next occurrence of a highlighted selection (which happens to be the same behavior in Atom, SublimeText and other modern code editors). For developers using CMD+D for its "original" purpose, when installing this plugin, it becomes annoying the sequence stop working for the selections and gets overwritten by this new behavior. For someone understanding what is happening, it is relatively easy to customize the VSCode keybinds to work around the issue.

Please, consider including some information with the description of the plugin explaining how to "correct" the behavior or consider the use of a different keybind for this purpose as this particular sequence is used for  "select next occurrence of selection" in popular modern code editors.

**Comment by invincibleJai** [comment]
thanks will look into this. As you suggested keybindings can be mapped to something else https://code.visualstudio.com/docs/getstarted/keybindings , this would be useful for someone else.

**Comment by invincibleJai** [comment]
Reverting `CMD+D` with `cmd+shift+d`, as this is not mapped to any shortcuts in vscode

**Comment by invincibleJai** [comment]
Closing as updated keybindings.
