### ISSUE TITLE
Extend known dependencies list

### ISSUE THREAD

**Issue by dospolov** [fabric8-analytics/fabric8-analytics-vscode-extension#259]
Hey guys,

how I can add some library to known dependency list?
![image](https://user-images.githubusercontent.com/670682/52349403-2ab75c00-2a2f-11e9-84b7-d1fa305569d5.png)

**Comment by invincibleJai** [comment]
Thank for reporting it and just for record, platform has an ingestion pipeline in place even for unknown dependencies so that next time if these dependencies appear it would be known to the platform.
