### ISSUE TITLE
Sort dependencies shown in stack report

### ISSUE THREAD

**Issue by invincibleJai** [fabric8-analytics/fabric8-analytics-vscode-extension#260]
Currently, dependencies shown in stack report are not sorted, needs to be sorted in alphabetical order.

<img width="1585" alt="screen shot 2019-02-06 at 11 58 34 pm" src="https://user-images.githubusercontent.com/5129024/52364504-5f490900-2a6b-11e9-99eb-32d171d8d4c0.png">

**Comment by dvandra** [comment]
@arajkumar @mathur07 

Can we close this issue as we are ordering on basis of CVSS Score and Confidence Score?

**Comment by mathur07** [comment]
@dvandra Ya we can close this.
