### ISSUE TITLE
Latest version shown for bootstrap is not upto date

### ISSUE THREAD

**Issue by invincibleJai** [fabric8-analytics/fabric8-analytics-vscode-extension#263]
Currently it's showing latest version for bootstrap is` 4.2.1` which is not latest as latest version as of now is `4.3.1`

<img width="916" alt="screen shot 2019-02-19 at 2 37 31 pm" src="https://user-images.githubusercontent.com/5129024/53003010-0a869480-3454-11e9-9f9b-ddf44a821071.png">

**Comment by msrb** [comment]
This is weird. I see the latest data (version 4.3.1) in S3. The version was analyzed by our platform on February 13 - the same day it was released. I suspect that graph ingestion failed and thus the latest version information in graph is not up-to-date.

These issues should go away once retry on graph side is implemented and once Yusuf's latest version changes are promoted to prod.

**Comment by invincibleJai** [comment]
Thanks for update @msrb

**Comment by msrb** [comment]
What caught my eye is the number of contributors. The stack report shows 30, but the actual number is ~1k: https://github.com/twbs/bootstrap. It could be a limitation of the GitHub API, or a bug in the GitHub worker (more likely).

**Comment by invincibleJai** [comment]
FYI @miteshvp @sivaavkd

**Comment by sivaavkd** [comment]
@invincibleJai I think we should track this as a bug in openshiftio repo

**Comment by abs51295** [comment]
<img width="1027" alt="screen shot 2019-03-08 at 2 16 31 pm" src="https://user-images.githubusercontent.com/13438222/54017710-dc6fb700-41ac-11e9-9596-075e4b62a6bf.png">

I also see contributors "NA" for all my dependencies in stack report. Dependencies include `ora, chalk, meow, co, execa`

**Comment by invincibleJai** [comment]
Closing as fixed for bootstrap. Feel free to reopen if not.
