### ISSUE TITLE
Experiencing 504 Gateway Time-out for component-analyses

### ISSUE THREAD

**Issue by invincibleJai** [fabric8-analytics/fabric8-analytics-vscode-extension#270]
LSP is powered via Component-analyses , and for jetty-server am experiencing intermittent `504 Gateway Time-out`

END-POINT : component-analyses/maven/org.eclipse.jetty:jetty-server/9.3.2.v20150730

TYPE: GET

Response : 

```
<html>
    <body>
        <h1>504 Gateway Time-out</h1>
The server didn't respond in time.
    </body>
</html>
```

It's intermittent

This problem is more frequent in case of Bulk Component analyses

**Comment by invincibleJai** [comment]
@samuzzal-choudhury @miteshvp FYI

**Comment by yzainee** [comment]
https://github.com/fabric8-analytics/fabric8-analytics-server/pull/470

**Comment by invincibleJai** [comment]
Closing it as looks good to me now, not observed recently

**Comment by invincibleJai** [comment]
@yzainee post 10-15 calls to component-analyses call start taking 17sec + 

<img width="1303" alt="Screenshot 2019-04-02 at 11 54 52 AM" src="https://user-images.githubusercontent.com/5129024/55380656-76bde300-553e-11e9-8e1c-a36f9d9fb473.png">

**Comment by invincibleJai** [comment]
Closing it, as have not observed any.
