### ISSUE TITLE
GPL v3 is not showing up as license conflict

### ISSUE THREAD

**Issue by pdaverh** [fabric8-analytics/fabric8-analytics-vscode-extension#271]
The following JS library is using GPL v3.0. Shouldn't that show up as a conflict?

"flickity": "2.1.0"

<img width="872" alt="Screen Shot 2019-03-15 at 6 48 40 AM" src="https://user-images.githubusercontent.com/48592473/54432725-9e641d00-46ef-11e9-94c4-49b5f2efa929.png">

**Comment by miteshvp** [comment]
@pdaverh - So in this case, GPL-3.0 synonym is not added in our dictionary. Hence it treats this license as unknown. Once we add the synonym to the list, it will work as expected.
@sunilk747 - please add the synonym for the said license.

**Comment by invincibleJai** [comment]
@sunilk747 any updates here ??

**Comment by sunilk747** [comment]
It has been fixed. It's currently on staging. Need to push it to production.

**Comment by invincibleJai** [comment]
Thanks @sunilk747, pls update relevant PR if needed and update the issue once done

**Comment by invincibleJai** [comment]
Closing as fixed. Feel free to reopen if not.

**Comment by arajkumar** [comment]
Closing as fixed. Feel free to reopen if not.
