### ISSUE TITLE
Unable to generate stack report for Maven pom.xml

### ISSUE THREAD

**Issue by jeffmaury** [fabric8-analytics/fabric8-analytics-vscode-extension#272]
When a report is to be generated for a pom.xml Maven must be invoked but the command generated is:
mvn -f "workspacefolder"

It causes an error, maybe it's Windows specific ?
We should a pom.xml

**Comment by invincibleJai** [comment]
Thanks @jeffmaury , it's been handled in https://github.com/fabric8-analytics/fabric8-analytics-vscode-extension/pull/268, even the command we use is being changed inorder to support transitive

**Comment by invincibleJai** [comment]
Closing as fixed
