### ISSUE TITLE
Intermittent: Sometime stackanalyses takes forever to complete

### ISSUE THREAD

**Issue by invincibleJai** [fabric8-analytics/fabric8-analytics-vscode-extension#283]
Sometime stackanalyses takes forever to complete and it's intermittent

Kubernetes client https://github.com/fabric8io/kubernetes-client  :: `ebb4a31b1a804003a6845b5febbc39b1` In prog forever	

Maven Project https://github.com/jleetutorial/maven-project :: `0998420daa3449f28a37d3e139a0e864` in prog forever

Response : 

```
{
    "error": "Analysis for request ID '0998420daa3449f28a37d3e139a0e864' is in progress"
}
```

**Comment by yzainee** [comment]
@invincibleJai I dont see any problem with the stack aggr call for 0998420daa3449f28a37d3e139a0e864. however, for the recommender call, i see an error

Failed retrieving insights data.
--
  | ('Connection aborted.', BadStatusLine("''",))

**Comment by yzainee** [comment]
Can you try a few more times and see if it fails.. then we can check the same for the req id to see if we see some pattern or is this something random

**Comment by invincibleJai** [comment]
@yzainee thanks, this looks random to me. However if you want to try can try in above repos as in issue description. 

If i encounter some more , will update thread

**Comment by invincibleJai** [comment]
Closing as fixed. Feel free to reopen if not.
