### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by ghmoore** [fabric8-analytics/fabric8-analytics-vscode-extension#287]
- Issue Type: `Performance`
- Extension Name: `fabric8-analytics`
- Extension Version: `0.0.11`
- OS Version: `Windows_NT x64 10.0.18362`
- VSCode version: `1.33.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`C:\Users\ghmoo\redhat.fabric8-analytics-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by invincibleJai** [comment]
thanks @ghmoore for reporting, webpack could help in reducing load time https://github.com/Microsoft/vscode-extension-samples/tree/master/webpack-sample

**Comment by invincibleJai** [comment]
@arajkumar you get more insights here https://github.com/Microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by arajkumar** [comment]
I did a CPU profiling & found nothing significant. @ghmoore , it would be very helpful if you could attach the file(`C:\Users\ghmoo\redhat.fabric8-analytics-unresponsive.cpuprofile.txt`) which is mentioned in the report.

Below is a startup profile of this extension.
[CPU-20190827T073114.484Z.cpuprofile.txt](https://github.com/fabric8-analytics/fabric8-analytics-vscode-extension/files/3544807/CPU-20190827T073114.484Z.cpuprofile.txt)

**Comment by arajkumar** [comment]
When I do a full stack analysis for [CHE project](https://github.com/eclipse/che/), it spikes upto 25%(4 cores, 100% in core?) when collecting dependency details using `mvn` utility. The spike is momentary and lasts for couple of seconds depends on the no.of deps & depth of the dependency graph. I did a similar test on pypi and npm. It is not even 25% spike seen for those eco systems.
