### ISSUE TITLE
Recommended version shown in component analyses and stack analyses are not Same

### ISSUE THREAD

**Issue by invincibleJai** [fabric8-analytics/fabric8-analytics-vscode-extension#292]
The recommended version shown in component analyses and stack analyses are not Same

Component-analyses:

<img width="531" alt="Screenshot 2019-04-22 at 9 16 39 PM" src="https://user-images.githubusercontent.com/5129024/56509270-2b4a9380-6544-11e9-85ef-4aeebf3fb8f4.png">

Stack-analyses: 

<img width="1106" alt="Screenshot 2019-04-22 at 9 16 18 PM" src="https://user-images.githubusercontent.com/5129024/56509295-41585400-6544-11e9-8921-4b52c2b2b91a.png">

**Comment by invincibleJai** [comment]
closing as fixed.

**Comment by invincibleJai** [comment]
@miteshvp have observed difference for dojo

Stack report: 

<img width="1172" alt="Screenshot 2019-05-06 at 10 52 11 AM" src="https://user-images.githubusercontent.com/5129024/57207736-0d256e80-6fed-11e9-9119-4f3419e33dd2.png">

LSP :

<img width="413" alt="Screenshot 2019-05-06 at 10 52 22 AM" src="https://user-images.githubusercontent.com/5129024/57207742-19113080-6fed-11e9-9d16-7d809f6a2adf.png">

**Comment by invincibleJai** [comment]
Similar for `express-cart@1.1.6` LS shows 1.1.7 and report shows 1.1.11

**Comment by yzainee** [comment]
https://github.com/fabric8-analytics/f8a-server-backbone/pull/153

**Comment by invincibleJai** [comment]
Closing as fixed. Feel free to reopen if not.
