### ISSUE TITLE
VsCode Extension - Dependency Details card needs minor improvements

### ISSUE THREAD

**Issue by miteshvp** [fabric8-analytics/fabric8-analytics-vscode-extension#295]
VsCode Extension Dependency Details card shows serial number besides a dependency name. As the number increases to triple digit, it gets mixed with the dependency name as seen in the below figure.
<img width="1016" alt="image" src="https://user-images.githubusercontent.com/17736013/56648346-cb1d3400-66a0-11e9-8012-5cfbd20e63f7.png">

Also, it will be nice to show all the dependency details in some alphabetical order for easy search in case the number of dependencies in a stack are higher.

**Comment by dvandra** [comment]
@arajkumar 
Can we close this issue as it is in the separate column in upcoming new release 0.0.14?

**Comment by arajkumar** [comment]
@dvandra Can you verify & close if it is not seen in the latest UI?

**Comment by dvandra** [comment]
This issue has been resolved.

https://github.com/fabric8-analytics/fabric8-analytics-stack-report-ui/pull/168
