### ISSUE TITLE
Quick fixes on hover don't show associated code actions however click on version does

### ISSUE THREAD

**Issue by invincibleJai** [fabric8-analytics/fabric8-analytics-vscode-extension#297]
Quick fixes on hover don't show associated code actions as below

<img width="1034" alt="Screenshot 2019-04-25 at 9 43 21 AM" src="https://user-images.githubusercontent.com/5129024/56709407-c14a0e00-673e-11e9-836f-79e3be347589.png">

However, on click of version shows Quick action and works as expected

<img width="574" alt="Screenshot 2019-04-25 at 9 43 34 AM" src="https://user-images.githubusercontent.com/5129024/56709424-e0e13680-673e-11e9-9cbb-bf4bdd53d15d.png">

**Comment by invincibleJai** [comment]
https://github.com/Microsoft/vscode/issues/71579

**Comment by dvandra** [comment]
@arajkumar 

Can we close this issue as Quick Fix is working now and will be available in next release 0.0.14??

**Comment by arajkumar** [comment]
Sure. @dvandra

**Comment by dvandra** [comment]
https://github.com/fabric8-analytics/fabric8-analytics-lsp-server/pull/118/files#diff-afd7474282d01269197c1d3f05651761R188

PR: https://github.com/fabric8-analytics/fabric8-analytics-lsp-server/pull/118
