### ISSUE TITLE
Stop polling for stack-report if it takes any longer than 120 secs 

### ISSUE THREAD

**Issue by invincibleJai** [fabric8-analytics/fabric8-analytics-vscode-extension#304]
Currently, extension stops polling in below scenarios at an interval of 6 sec
- in case of any HTTP Error
- in case of successful response with 200
 
Stop polling for stack-report if it takes any longer than 120 secs.

**Comment by arajkumar** [comment]
It would be better if user configures the timeout.

**Comment by invincibleJai** [comment]
@arajkumar this can be closed and I don't think the user should be exposed with this as this is internal of the platform.

**Comment by samuzzal-choudhury** [comment]
@SriKrishnaPaparaju 
From the server-side, on receiving a `/stack-analyses [GET]`, I will introduce a check to find the delta between the current time and the request submission time, which if exceeds a configurable time interval (for example, 120 seconds), the server would return an HTTP error 408(Request Timeout).

The client will then have to understand this new status code from the `stack-analyses GET` and stop polling for that request ID immediately.

cc: @invincibleJai @arajkumar

**Comment by SriKrishnaPaparaju** [comment]
@invincibleJai @arunkumars08 can we change the extension code to 'stop calling GET after 20 secs. ' ?

**Comment by invincibleJai** [comment]
yes i already did this https://github.com/fabric8-analytics/fabric8-analytics-vscode-extension/pull/305, @arajkumar can you pls modify counter and time bases on above

**Comment by samuzzal-choudhury** [comment]
@SriKrishnaPaparaju @invincibleJai @arajkumar I am planning for a default request timeout on the server-side of 120 seconds. Hope that's fine with you all.

**Comment by arajkumar** [comment]
@SriKrishnaPaparaju @invincibleJai @samuzzal-choudhury Timeout should be 20 or 120?

Currently it is polling for 17 times in 7 sec interval.

**Comment by samuzzal-choudhury** [comment]
The changes have been moved to production. Hence, closing the issue.
