### ISSUE TITLE
[BUG] LS not showing fix for libnmap

### ISSUE THREAD

**Issue by invincibleJai** [fabric8-analytics/fabric8-analytics-vscode-extension#306]
**Describe the bug**
for `"libnmap": "0.4.15"`shows CVE in LS but not getting any recommended fix. Though it shows up in the stack report as expected.

**To Reproduce**
same dependencies used: 

```
"dependencies": {
		"ansi-styles": "^3.2.1",
		"escape-string-regexp": "^1.0.5",
		"supports-color": "^5.5.0",
		"bootstrap": "4.1.1",
		"dojo": "1.13.3",
		"libnmap": "0.4.15"
	}
```

**Expected behavior**
Should show recommended fix via LS.

**Comment by invincibleJai** [comment]
@sivaavkd FYI

**Comment by invincibleJai** [comment]
Similar issue with `"whereis": "0.4.0"`

**Comment by yzainee** [comment]
This can be because of the recommended version (latest version) which is shown in the stack report is missing in the graph, hence not showing up in vscode.
All the versions that are present in the graph for the above mentioned pkgs have a CVE associated with them. Hence we cannot recommend that to the user.
@invincibleJai cc: @miteshvp

**Comment by invincibleJai** [comment]
@yzainee in that case even in stack report we shouldn't show any recommended fix, How are we showing there? `libnmap 0.4.15 has CVE and 0.4.16 is safe` 

Shouldn't it be consistent??

**Comment by yzainee** [comment]
@invincibleJai Because its blindly taking the value of the latest version and showing it up, without checking if that version exists in our graph db. I need to fix that. The issue is same as mentioned in #292

**Comment by yzainee** [comment]
https://github.com/fabric8-analytics/f8a-server-backbone/pull/153

**Comment by yzainee** [comment]
Have tested all the points mentioned in the bug. its not reproducible now. The version fixes have resolved this problem.

**Comment by yzainee** [comment]
Jira: https://jira.coreos.com/browse/APPAI-784
