### ISSUE TITLE
[BUG]Shows unknown license without any conflicting or unknown license

### ISSUE THREAD

**Issue by invincibleJai** [fabric8-analytics/fabric8-analytics-vscode-extension#307]
**Describe the bug**
Shows unknown license without any conflicting or unknown license

**To Reproduce**
same dependencies used: 

```
"dependencies": {
		"ansi-styles": "^3.2.1",
		"escape-string-regexp": "^1.0.5",
		"supports-color": "^5.5.0",
		"bootstrap": "4.1.1",
		"dojo": "1.13.3",
		"libnmap": "0.4.15"
	}
```

**Expected behavior**
Should show conflict/unknown license if unable to suggest

**Screenshots**

<img width="1362" alt="Screenshot 2019-05-06 at 11 04 17 AM" src="https://user-images.githubusercontent.com/5129024/57207993-c0429780-6fee-11e9-9276-729e63771159.png">

**Comment by invincibleJai** [comment]
@sunilk747 FYI

**Comment by sunilk747** [comment]
@invincibleJai This is the scenario when we were unable to find the package level license of one of the dependencies. Either the license is not known to us or we couldn't find a synonym for the license. If you could provide the stack id of the above stack analysis call I can debug more.

**Comment by invincibleJai** [comment]
@sunilk747 i have provided deps in issue , pls generate one ;)

**Comment by sunilk747** [comment]
Yeah sure.

**Comment by yzainee** [comment]
https://github.com/openshiftio/saas-analytics/pull/706
