### ISSUE TITLE
Cmd doesn't work as expected if just manifest file is opened

### ISSUE THREAD

**Issue by invincibleJai** [fabric8-analytics/fabric8-analytics-vscode-extension#312]
Current behavior:

1) open package.json file in VSCode (but not the whole project)

2) start the Analysis from context menu -> it works

3) start the Analysis via Ctrl+Shift+D -> it displays the message Cannot read property 'length' of undefined (and the analysis is displayed)

 

Expected behavior:

1) the same

2) the same

3) the message won't be shown

**Comment by arajkumar** [comment]
It is already fixed in the master(#314).
