### ISSUE TITLE
[BUG] VSCode comment not working

### ISSUE THREAD

**Issue by hemangajmera** [fabric8-analytics/fabric8-analytics-vscode-extension#313]
Once this extension is added, and if I do `Ctrl + /` for commenting any line in any xml file, it uses java language comment instead of xml comment. This extension should not affect comment.

In short expected `<!--` and  `-->` for any xml file, but getting `//` in the beginning of line when invoke `Ctrl /` shortcut

**Comment by arajkumar** [comment]
@hemangajmera , I couldn't reproduce the issue with the vscode 1.36.1., hence closing this. Feel free to reopen the issue along with steps to reproduce. Thanks.

**Comment by arajkumar** [comment]
@hemangajmera , I couldn't reproduce the issue with the vscode 1.36.1., hence closing this. Feel free to reopen the issue along with steps to reproduce. Thanks.

**Comment by arajkumar** [comment]
I will wait for feedback from other developers. cc: @miteshvp @invincibleJai @SriKrishnaPaparaju @SamuelStuchly

**Comment by arajkumar** [comment]
Couldn't reproduce it.
