### ISSUE TITLE
[BUG] Mismatch between count for security issues and number of dependencies affected with the security issues

### ISSUE THREAD

**Issue by SriKrishnaPaparaju** [fabric8-analytics/fabric8-analytics-vscode-extension#316]
**Describe the bug**

**To Reproduce**
1. Go to '...' Create application stack report on gitbhub.com/fabric8-analytics/analytics-server
<img width="1629" alt="Screen Shot 2019-07-31 at 7 48 23 AM" src="https://user-images.githubusercontent.com/42730908/62178781-dc44a380-b367-11e9-8a2c-7660906c2d95.png">

**Expected behavior**

**Screenshots**

**Logs**
If applicable, attach logs.

**VSCode(please complete the following information):**
 - OS: [e.g. macOS]
 - VSCode version [e.g. 1.33.1]
 - Dependency Analytics Version [e.g. 0.0.22]

**CHE7/Theia(please complete the following information):**
 - OS: [e.g. macOS]
 - Browser [e.g. chrome]
 - CHE/Theia version 
 - Dependency Analytics Version [e.g. 0.0.22]

**Additional context**

cc @sivaavkd @arajkumar

**Comment by sivaavkd** [comment]
@SriKrishnaPaparaju  can you share the screenshot with transitive tab ?  
Please note:  For example, if one package has 3 cves and another one has 1 cve, total is shown as 4 cves.  However, we are showing distinct packages count with cves on the tab title.  I think, we have to be consistent here
