### ISSUE TITLE
[BUG] Extension is not working properly with some of the python versions 

### ISSUE THREAD

**Issue by sivaavkd** [fabric8-analytics/fabric8-analytics-vscode-extension#319]
**Describe the bug**
with python 3.6, the stack report is generated properly for a given requirements.txt.  whereas for python 3.4, the stack report is not complete.

**To Reproduce**
1. in settings.json of VSCode, set PythonPath to 3.6
2. see that stack report is generated properly.
3. Change the PythonPath to 3.4 and generate stack report for the same project.
4. See that the stack report is generated, but not complete.  the number of analyzed packages are less and number of transitive packages are also less.

**Expected behavior**
For the same project, the stack report should be identical for various python versions.

@anuragtr @samuzzal-choudhury  please add screenshots if you have any. cc @arajkumar

**Comment by arajkumar** [comment]
It is upto the project to decide which python to support. Some dependencies may not available for older pythons.

For e.g. `Sphinx==2.0.0` from our rudra module needs `python >= 3.5`, You can verify it by downloading the dependency from [PyPI](https://files.pythonhosted.org/packages/17/a4/338f9cbc334dd27c972ea9aae3e054068c9b3a642c8abb1f67f93a59a85e/Sphinx-2.0.0-py2.py3-none-any.whl#sha256=5a54f9132766c8ffdd4021de4d0ef8afeb93235569d64b617612e60070332583)., looks for METADATA file.

```
...
Requires-Python: >=3.5
Description-Content-Type: text/x-rst
Requires-Dist: sphinxcontrib-applehelp
Requires-Dist: sphinxcontrib-devhelp
Requires-Dist: sphinxcontrib-jsmath
Requires-Dist: sphinxcontrib-htmlhelp
Requires-Dist: sphinxcontrib-serializinghtml
Requires-Dist: sphinxcontrib-qthelp
...
```

**Comment by arajkumar** [comment]
@anuragtr @samuzzal-choudhury , Please verify it.
