### ISSUE TITLE
[BUG] wrong report is shown to user when pip install fails

### ISSUE THREAD

**Issue by sivaavkd** [fabric8-analytics/fabric8-analytics-vscode-extension#327]
**Describe the bug**
Some times, "pip install' may fail because of either permission issues or python version issues etc.  In such scenarios, we should show error message on VSCode, rather than showing a stack report with partial data.
Also, we should indicate somewhere in the documentation that pip install should work properly in order for our stack report to show up - and the trouble shooting tips in case it doesn't work.
**To Reproduce**

**Expected behavior**

**Screenshots**

**Logs**
If applicable, attach logs.

**VSCode(please complete the following information):**
 - OS: [e.g. macOS]
 - VSCode version [e.g. 1.33.1]
 - Dependency Analytics Version [e.g. 0.0.22]

**CHE7/Theia(please complete the following information):**
 - OS: [e.g. macOS]
 - Browser [e.g. chrome]
 - CHE/Theia version 
 - Dependency Analytics Version [e.g. 0.0.22]

**Additional context**

**Comment by sivaavkd** [comment]
cc @arajkumar

**Comment by arajkumar** [comment]
It is fixed by PR #333 .
