### ISSUE TITLE
[BUG] [Maven] License analysis is failing for Eclipse che pom.xml

### ISSUE THREAD

**Issue by arajkumar** [fabric8-analytics/fabric8-analytics-vscode-extension#329]
Here is the API response:

[https://gist.github.com/arajkumar/c59acddb10ba71b7d4b153c879b2b9a5#file-res-json-L1460

]

Following error is seen in the response:

"license_analysis": {
"reason": "Some unexpected exception happened!",
"status": "Failure",
"outlier_packages": [],
"unknown_licenses":

{ "really_unknown": [], "component_conflict": [] }
,
"conflict_packages": [],
"f8a_stack_licenses": [],
"current_stack_license": {}
},

**Comment by yzainee** [comment]
https://github.com/fabric8-analytics/fabric8-analytics-license-analysis/pull/196
https://github.com/fabric8-analytics/fabric8-analytics-license-analysis/pull/197
