### ISSUE TITLE
Remove req header which enables transitive report by default

### ISSUE THREAD

**Issue by arajkumar** [fabric8-analytics/fabric8-analytics-vscode-extension#331]
PR #330 has to be reverted once transitive report is enable from platform side by default.

**Comment by arajkumar** [comment]
@SriKrishnaPaparaju , api server has to enable transitive by default, which will happen post 0.13.

**Comment by dvandra** [comment]
@arajkumar 
Do we need rollback for some previous changes, for which this issue was created?

**Comment by arajkumar** [comment]
@dvandra Don't do anything as of now.
