### ISSUE TITLE
Remove reference to mattermost channel in readme and vscode marketplace descriptors

### ISSUE THREAD

**Issue by pdaverh** [fabric8-analytics/fabric8-analytics-vscode-extension#332]
Problem

The mattermost channel link mentioned in the readme and shown in vscode marketplace is no longer operational.

Solution
Remove references to the mattermost channel from the readme and vscode marketplace descriptor for the extension.

**Comment by arajkumar** [comment]
It will be addressed as part of #326.

**Comment by arajkumar** [comment]
@sivaavkd  had already fixed it it as part of #326. Thanks @sivaavkd !
