### ISSUE TITLE
[BUG] Dependency Details Card layout/content changes when transitive_count is zero

### ISSUE THREAD

**Issue by miteshvp** [fabric8-analytics/fabric8-analytics-vscode-extension#336]
**Describe the bug**
Any manifest which does not have any transitives, shows the below card.
<img width="1087" alt="image" src="https://user-images.githubusercontent.com/17736013/63683388-dc757900-c817-11e9-9027-d71f6a7d3d6c.png">

**To Reproduce**
Any manifest which does not have any transitive dependencies, will be able to reproduce.

**Expected behavior**
Dependency Details card should show Analyzed Direct, Analyzed Transitive and Unknown Dependencies details.
An example snapshot
<img width="1087" alt="image" src="https://user-images.githubusercontent.com/17736013/63683689-a7b5f180-c818-11e9-8029-9bcd265deb9a.png">

**VSCode(please complete the following information):**
 - OS: macOS
 - VSCode version 1.37.1
 - Dependency Analytics Version 2019.8.23

**Comment by arajkumar** [comment]
@miteshvp 

I analysed the API response with & without `showTransitiveReport: true` header, in both the cases I see that the JSON response include `transitive_count` field. Please refer the following attachments,

[51f4d5f02c464ddcb728623bffb948f1.with.trans.json.txt](https://github.com/fabric8-analytics/fabric8-analytics-vscode-extension/files/3541657/51f4d5f02c464ddcb728623bffb948f1.with.trans.json.txt)
[8858d47ea9f045e6a64ac7fd9fe97d01.no.trans.json.txt](https://github.com/fabric8-analytics/fabric8-analytics-vscode-extension/files/3541658/8858d47ea9f045e6a64ac7fd9fe97d01.no.trans.json.txt)

Actually stack analysis report UI's presentation is based on `transitive_count` field, so it must be either removed / set to -1 incase transitive support is not enabled from VSIX side.

https://github.com/fabric8-analytics/fabric8-analytics-stack-report-ui/blob/a14e0dff4a538ca887f2b888dd24992afb7db926/src/app/stack/report-summary/report-summary.component.ts#L132

**Comment by miteshvp** [comment]
@arajkumar Yes, that is expected to have transitive_count field. Question is, how come there are two different UI layouts for the similar JSON structure which includes `transitive_count` in both.

**Comment by arajkumar** [comment]
if `transitive_count > 0` then direct + transitive + unknown card would be displayed, otherwise total + analysed + unknown card would be displayed.

**Comment by miteshvp** [comment]
I am ok with this different content based on transitive is > 0 or not. If @SriKrishnaPaparaju is ok with showing different cards.

**Comment by arajkumar** [comment]
@miteshvp , The condition was used to keep running the stack analysis UI for VSIX <= 0.0.12. I think the better approach would to set `transitive_count` to `-1` from platform side if `showTransitiveReport=false`

**Comment by miteshvp** [comment]
That's not feasible. This touches 3-4 different services in the backend. It requires changes in all the places. I don't know how challenging it is to handle at front-end, but TBH, we have transitives enabled by default now, and we should stick to once card content.
