### ISSUE TITLE
Update Jetbrains marketplace overview

### ISSUE THREAD

**Issue by pdaverh** [fabric8-analytics/fabric8-analytics-vscode-extension#342]
The overview content shown in Jetbrains marketplace for the IDE plug-in (https://plugins.jetbrains.com/plugin/12541-dependency-analytics) should be similar to that of VS Code, except the stack analysis report capability which is not available. The overview should include screenshots/gifs of the analysis offered by the plug-in in JetBrains IDEs. The version number of the release should match with VS Code Marketplace.

**Comment by arajkumar** [comment]
Hello @pdaverh , Thanks for reporting. This particular issue should be raised against https://github.com/redhat-developer/intellij-dependency-analytics repo.
