### ISSUE TITLE
[BUG] Transitive security issues tab is not populated with single click

### ISSUE THREAD

**Issue by arajkumar** [fabric8-analytics/fabric8-analytics-vscode-extension#344]
**Describe the bug**
On the stack report UI, Transitive security issues tab is not populated with single click. It needs two clicks to populate on very first time. Further selection works with single click.

**To Reproduce**
1. Generate full stack report, by default "Security Issues" card will be selected
2. Click on "Transitive Dependencies with Security Issues" tab
3. It won't be populated unless you click again

**Expected behavior**
It should be populated on first click

**Comment by dvandra** [comment]
@arajkumar 
Can we close this issue as we have new tabs with "Commonly known Vulnerabilities" and "Vulnerabilities unique to Snyk" and it is working as expected as it will be available in next release 0.0.14?

**Comment by arajkumar** [comment]
@mathur07 I still see same issue. Can you look into this?

**Comment by mathur07** [comment]
@arajkumar ya i can take it up.

**Comment by dvandra** [comment]
> @mathur07 I still see same issue. Can you look into this?

Are you able to see this in the new version 0.0.14-xyz?
