### ISSUE TITLE
Change tab name from 'Unknown License(s) Details' to something like 'Dependencies with Unknown License(s)'

### ISSUE THREAD

**Issue by anuragtr** [fabric8-analytics/fabric8-analytics-vscode-extension#355]
**Describe the bug**
In the report UI, number of 'Unknown licenses' is 1 more than the number shown in 'Unknown licenses details'.

**To Reproduce**
1. generate report for python project
2. issue would get replicated and could be seen in UI
3. Try with repos:
    - https://github.com/fabric8-analytics/fabric8-analytics-rudra
    - https://github.com/fabric8-analytics/f8a-stacks-report

**Expected behavior**
Number of 'Unknown licenses' displayed should be same as the number shown in 'Unknown licenses details'.

**Screenshots**

**Logs**
If applicable, attach logs.

**VSCode(please complete the following information):**
 - OS: Fedora
 - VSCode version: 1.36.1
 - Dependency Analytics Version: [VSIX: fabric8-analytics-2019.9.12.vsix]

**CHE7/Theia(please complete the following information):**
 - OS: [e.g. macOS]
 - Browser [e.g. chrome]
 - CHE/Theia version 
 - Dependency Analytics Version [e.g. 0.0.22]

**Additional context**

**Comment by yzainee** [comment]
checked with the stack report repo. The behaviour is correct. The number of unknown licenses show as 7. Under unknwon license details, we group the licenses under the dependencies and not the other way round. So if there is one dep which contains 2 unknown licenses, it is going to display it like that.
I dont see any correction required from our side.

**Comment by anuragtr** [comment]
thanks @yzainee then its expected behavior and can close this issue.
As dicsussed, to avoid user from getting confused, we can change the label from 'Unknown License(s) Details' to something like 'Dependencies with Unknown License(s)'
cc: @arajkumar

**Comment by anuragtr** [comment]
@arajkumar to avoid this confusion I think we should change the tab names from 'Unknown License(s) Details' to something like 'Dependencies with Unknown License(s)' and similarly for 'Conflicting License(s) Details' to something like 'Dependencies with Conflicting License(s)'. WDYT?
I discussed this with Yusuf, renamed the issue and assigning to you.

**Comment by dvandra** [comment]
@arajkumar 
Do we have to address this issue in release 0.0.14?

**Comment by dvandra** [comment]
Thanks @mathur07 
Closing the issue mark as resolved!
