### ISSUE TITLE
Implement a simple virtual env to deal with python dependencies

### ISSUE THREAD

**Issue by arajkumar** [fabric8-analytics/fabric8-analytics-vscode-extension#356]
**Is your feature request related to a problem? Please describe.**
In order to get dependency details right, we do `pip install --user requirements.txt` before collecting dependency details for a python stack. Since we don't explicitly use any virtual env, we are polluting the extension user's environment. See #353 

**Describe the solution you'd like**
Create a simplified virtual env just for `pip install`. This can be achieved by pointing a `HOME` env variable to a different location(preferably with in user stack, e.g. `<path-to-src>/.redhat-dependency-analytics/fakehome`. This should be done only for our extension's `pip install`.
```
export HOME=/tmp/test # Just for demonstration
pip install --user flask==0.12
pip show flask # Location: field will be pointing a new HOME
pip freeze 
```
Also we should consider exposing a `fakehome` location as an extension settings.

**Describe alternatives you've considered**
Other lite weight virtual envs are not really lite for us.

**Comment by arajkumar** [comment]
@SriKrishnaPaparaju @miteshvp @rootAvish Do you see any downsides with this?

**Comment by rootAvish** [comment]
I like this solution. I'm assuming the fake-home thing works on Windows too?
