### ISSUE TITLE
[BUG] Visual artifact seen after taking corrective action from lsp

### ISSUE THREAD

**Issue by arajkumar** [fabric8-analytics/fabric8-analytics-vscode-extension#357]
**Describe the bug**
When the library version is updated by clicking on the recommendation, there is still a partial underline left after the version number. There is no space after the last digit.

**To Reproduce**
1. Open requirments.txt which has CVEs
2. Click the light bulb and do the corrective measure suggested by LSP
3. See artifact at the end

**Screenshots**
![image](https://user-images.githubusercontent.com/3874763/64859260-6199c400-d647-11e9-95b2-f53efe4c320e.png)

Raised by @Parag.

See https://jira.coreos.com/browse/APPAI-346

**Comment by dvandra** [comment]
@arajkumar after taking corrective action from lsp with quick fix, those changes should be saved 1st and as soon as we save the changes made by quick fix it will not show the partial underline left after the version number.

Please correct me if i am wrong!
