### ISSUE TITLE
Support Yarn package manager for node

### ISSUE THREAD

**Issue by arajkumar** [fabric8-analytics/fabric8-analytics-vscode-extension#361]
**Is your feature request related to a problem? Please describe.**
Currently we support only `npm` based node ecosystem. `yarn` is also a popular one we should consider it too.

`yarn` does uses the same set of packages from `npm` registry., it just an another tool to manage & resolve dependencies.

https://yarnpkg.com/lang/en/

**Comment by n0mer** [comment]
@arajkumar any updates on this ?

**Comment by ajubin** [comment]
I'll be happy to help also :)

**Comment by abbytec** [comment]
Please, also add pnpm, because it is frecuently used too (as yarn / npm)

**Comment by digeomel** [comment]
I disabled the extension because of this. It was popping up all the time with a warning, trying to use npm to install modules, when we use yarn (and we have a yarn.lock file).

**Comment by willmakley** [comment]
I don't care if you add support, but you need to detect yarn.lock and stop generating package-lock.json in projects that don't use it.
