### ISSUE TITLE
[BUG] Opening manifest file does not show the scanned results

### ISSUE THREAD

**Issue by spaparaju** [fabric8-analytics/fabric8-analytics-vscode-extension#365]
**Describe the bug**
Opening manifest file does not show the scanned results indicating the # of dependencies with vulnerabilities. 

**To Reproduce**
Open a manifest file to see if the notification pops up (at the bottom right corner) indicating the # of dependencies with vulnerabilities
**Expected behavior**
Opening manifest file  show (as a notification at the bottom right corner of VSCode) the scanned results indicating the # of dependencies with vulnerabilities. This notification (at the bottom right corner of the VSCode window) would need to show up even for a case of a manifest file with zero vulnerabilities.

**Screenshots**

**Logs**
If applicable, attach logs.

**VSCode(please complete the following information):**
 - OS:  macOS
 - VSCode version: 1.41.0
 - Dependency Analytics Version: 0.0.13

**CHE7/Theia(please complete the following information):**
 - OS: [e.g. macOS]
 - Browser [e.g. chrome]
 - CHE/Theia version 
 - Dependency Analytics Version [e.g. 0.0.22]

**Additional context**

**Comment by SriKrishnaPaparaju** [comment]
@arajkumar do we know the cause for this bug ?

**Comment by arajkumar** [comment]
@SriKrishnaPaparaju, somehow I missed this bug. Let me quickly check.

**Comment by arajkumar** [comment]
@SriKrishnaPaparaju Do you see this problem with a specific manifest? I tried with couple of manifests and I see the notification all the time.

**Comment by dvandra** [comment]
@spaparaju @arajkumar 

Are we good to close this issue?

**Comment by dvandra** [comment]
@arajkumar @spaparaju Closing this issue, please reopen the issue if you are not able to see the notification.
