### ISSUE TITLE
[BUG] Generation of stack report is timing out

### ISSUE THREAD

**Issue by SriKrishnaPaparaju** [fabric8-analytics/fabric8-analytics-vscode-extension#369]
**Describe the bug**

**To Reproduce**
    Generate stack report on https://github.com/fabric8-analytics/fabric8-analytics-jenkins-plugin
 408 timing out
**Expected behavior**

**Screenshots**

*
<img width="1262" alt="Screen Shot 2020-03-02 at 7 36 53 PM" src="https://user-images.githubusercontent.com/42730908/75742837-ef23ba00-5d34-11ea-9067-028aed60f056.png">
*Logs**
If applicable, attach logs.

**VSCode(please complete the following information):**
 - OS: [e.g. macOS]
 - VSCode version [e.g. 1.33.1]
 - Dependency Analytics Version [e.g. 0.0.22]  0.0.13

**CHE7/Theia(please complete the following information):**
 - OS: [e.g. macOS]
 - Browser [e.g. chrome]
 - CHE/Theia version  
 - Dependency Analytics Version [e.g. 0.0.22]
**Additional context**

**Comment by no-on3** [comment]
I got the same screen:
```
Version: 1.40.1
Commit: 8795a9889db74563ddd43eb0a897a2384129a619
Date: 2019-11-13T16:49:30.162Z
Electron: 6.1.2
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Linux x64 5.5.6-1-MANJARO
```
`Version : 0.0.13 
`

**Comment by deepak1725** [comment]
@no-on3 Can you please share your `package.json` ?

**Comment by no-on3** [comment]
> @no-on3 Can you please share your `package.json` ?

`{
  "name": "backend",
  "private": true,
  "version": "0.0.1",
  "description": "edifica backend",
  "keywords": [],
  "dependencies": {
    "@sailshq/connect-redis": "^3.2.1",
    "@sailshq/lodash": "^3.10.3",
    "@sailshq/socket.io-redis": "^5.2.0",
    "axios": "^0.19.0",
    "bcrypt": "^3.0.5",
    "compression": "^1.7.4",
    "cron": "^1.7.1",
    "currency-formatter": "^1.5.5",
    "ejs": "^2.7.1",
    "grunt": "1.0.1",
    "jayson": "^3.0.1",
    "jsonwebtoken": "^8.5.1",
    "jwt-policy": "^0.7.0",
    "moment": "^2.24.0",
    "nested-pop": "^0.1.4",
    "node-pdftk": "^2.1.1",
    "nodemailer-mailgun-transport": "^1.4.0",
    "passport": "^0.4.0",
    "passport-jwt": "^4.0.0",
    "passport-local": "^1.0.0",
    "pdffiller": "0.0.10",
    "puppeteer": "^1.20.0",
    "request": "^2.88.0",
    "request-promise": "^4.2.4",
    "sails": "^1.1.0",
    "sails-hook-email": "^0.12.1",
    "sails-hook-grunt": "^3.1.0",
    "sails-hook-orm": "^2.1.1",
    "sails-hook-sockets": "^1.5.5",
    "sails-mysql": "^1.0.1",
    "soap": "^0.27.1",
    "util": "^0.12.1"
  },
  "devDependencies": {
    "@sailshq/eslint": "^4.19.3",
    "eslint": "^5.16.0",
    "eslint-config-prettier": "^4.1.0",
    "eslint-plugin-prettier": "^3.0.1",
    "nodemon": "^1.18.10",
    "npm-run-all": "^4.1.5",
    "prettier": "^1.16.4"
  },
  "scripts": {
    "dev": " nodemon --inspect=127.0.0.1:9230 app.js",
    "staging": "BASE=staging NODE_ENV=production pm2 start --name 'edificarcd-backend-staging' app.js",
    "prod": "BASE=prod NODE_ENV=production pm2 start --name 'edificarcd-backend-prod' app.js",
    "stop:staging": "pm2 delete edificarcd-backend-staging",
    "stop:prod": "pm2 delete edificarcd-backend-prod",
    "lift:prod": "BASE=prod NODE_ENV=production sails lift",
    "lift:dev": "LOG_QUERIES=true DEBUG=query NODE_ENV=development sails lift --alter --hookTimeout=360000",
    "lift:prod:k8s": "NODE_ENV=production K8S=true sails lift",
    "lift:dev:k8s": "NODE_ENV=development K8S=true sails lift --alter --hookTimeout=360000 --port=7001",
    "prod:k8s": "npm run lift:dev:k8s"
  },
  "main": "app.js",
  "repository": {
    "type": "git",
    "url": "git://github.com/oussama/backend.git"
  },
  "author": "oussama",
  "license": "",
  "engines": {
    "node": "^10.11"
  }
}
`

**Comment by SriKrishnaPaparaju** [comment]
fixed by https://github.com/openshiftio/saas-analytics/pull/785
