### ISSUE TITLE
Remedial version is not shown for vulnerabilities related to transitive dependencies

### ISSUE THREAD

**Issue by spaparaju** [fabric8-analytics/fabric8-analytics-vscode-extension#370]
**Is your feature request related to a problem? Please describe.**
Remedial version is not shown for vulnerabilities related to transitive dependencies
**Describe the solution you'd like**
Remedial version needs to be shown for vulnerabilities related to transitive dependencies
**Describe alternatives you've considered**

**Additional context**
<img width="1592" alt="Screen Shot 2020-03-04 at 8 34 40 AM" src="https://user-images.githubusercontent.com/42730908/75841155-075a0e80-5df3-11ea-8844-6c66ca7c2aba.png">

**Comment by mathur07** [comment]
@prashbnair @arajkumar Showing the latest version of transitive dep. help here?

**Comment by prashbnair** [comment]
@mathur07  we can show the fix version for this package but that will not make the issue go away as it is a transitive.

**Comment by gorkem** [comment]
@prashbnair  whatever happened to the transitive dependencies? I do not see this report at all anymore.

**Comment by prashbnair** [comment]
@gorkem Are you not able to see the full stack report?

**Comment by gorkem** [comment]
I do not see a transitive dependencies section

**Comment by prashbnair** [comment]
![image](https://user-images.githubusercontent.com/7577395/113659114-f8f9b880-96be-11eb-89be-5e7b80de361a.png)

If your transitives have vulnerabilities it should listed.
