### ISSUE TITLE
Can't generate Dependency Analytics Report for requirements.txt

### ISSUE THREAD

**Issue by OutOfFocus4** [fabric8-analytics/fabric8-analytics-vscode-extension#398]
When I right-click `requirements.txt` in my Python project and select `Dependency Analytics Report`, an error message pops up:
```
ERROR: Can not perform a '--user' install. User site-packages are not visible in this virtualenv.
```

My project uses a virtual environment generated using the Python standard library's `venv` package

## System Info

* OS: MacOS 10.15.5 (19F101)
* Extension Version: 0.1.0
* VSCode:
  * Version: 1.47.0
  * Commit: d5e9aa0227e057a60c82568bf31c04730dc15dcd
  * Date: 2020-07-09T08:01:54.115Z
  * Electron: 7.3.2
  * Chrome: 78.0.3904.130
  * Node.js: 12.8.1
  * V8: 7.8.279.23-electron.0
  * OS: Darwin x64 19.5.0

**Comment by prashbnair** [comment]
This seems like an issue in your python environment, are you able to run
pip install -r requirements.txt

**Comment by OutOfFocus4** [comment]
`pip install -r requirements.txt` works fine.

However, `pip install --user -r requirements.txt` prints

```
ERROR: Can not perform a '--user' install. User site-packages are not visible in this virtualenv.
```

I have found that if I edit my environment's `pyvenv.cfg` from

```ini
home = /usr/local/opt/python/bin
include-system-site-packages = false
version = 3.7.8
```

to

```ini
home = /usr/local/opt/python/bin
include-system-site-packages = true
version = 3.7.8
```

then the problem goes away.

**Comment by OutOfFocus4** [comment]
Just installed version 0.2.0. I’m still getting the error.
