### ISSUE TITLE
[Enhancement] Vulnerable dependencies without version values in manifest file are not underlined.

### ISSUE THREAD

**Issue by pdaverh** [fabric8-analytics/fabric8-analytics-vscode-extension#399]
**Describe the bug**
If a library does not have a version explicitly assigned in the manifest file, and it happens to have a vulnerability, then the language server analysis does not underline the library. 

**To Reproduce**
1. Add a dependency in the manifest file that has known vulnerabilities and remove the version number
2. Save and open the manifest file and wait for the analysis to be done.
3. View the stack analysis report to see the vulnerability and switch back to the editor to see that the vulnerability is not shown.
**Expected behavior**
The library should be underlined with fix recommendation.
Developer should be able to update the manifest file with the recommended version.

**Screenshots**
Screenshot is attached.

- Dependency Analytics Version 0.1.0

<img width="176" alt="Screen Shot 2020-07-14 at 10 56 01 AM" src="https://user-images.githubusercontent.com/48592473/87454911-dfa95d00-c5c1-11ea-9e93-eb960289a047.png">
<img width="1057" alt="Screen Shot 2020-07-14 at 11 05 23 AM" src="https://user-images.githubusercontent.com/48592473/87454985-0071b280-c5c2-11ea-8d64-2a7ed2f8f1a2.png">

**Comment by prashbnair** [comment]
We do have issues with semantic versioning so this is similar. Component analysis expects a package and the exact version currently.

**Comment by IlonaShishov** [comment]
Outdated, closing this issue.
