### ISSUE TITLE
[BUG] Can not navigate to synk

### ISSUE THREAD

**Issue by gorkem** [fabric8-analytics/fabric8-analytics-vscode-extension#400]
**Describe the bug**
Sign up with snyk links and buttons on the vulnerabilities unique to Snyk does not work 
Fails with 
```
[Embedded Page] Blocked opening 'https://app.snyk.io/signup/?utm_medium=Partner&utm_source=RedHat&utm_campaign=Code-Ready-Analytics-2020&utm_content=Register' in a new window because the request was made in a sandboxed frame whose 'allow-popups' permission is not set.
```

This is on vscode 
```
Version: 1.47.1
Commit: 485c41f9460bdb830c4da12c102daff275415b53
Date: 2020-07-13T22:43:02.577Z (19 hrs ago)
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.5.0
```

![synk-signup](https://user-images.githubusercontent.com/82738/87463528-89e3ad80-c5df-11ea-9f66-75837b8f4199.gif)

**Comment by arajkumar** [comment]
@gorkem Thanks for reporting. It is a known vscode issue due to it's sandboxing strictness. You can use cmd + click(on mac), ctrl + click(on linux or windows) to open a hyper link. We are testing other workarounds to fix this issue.
