### ISSUE TITLE
Add Java Gradle support

### ISSUE THREAD

**Issue by ebramirez** [fabric8-analytics/fabric8-analytics-vscode-extension#405]
**Is your feature request related to a problem? Please describe.**
Currently there is no support for Gradle Java projects but Snyk supports it.

**Describe the solution you'd like**
Add Gradle support for Java projects.

**Comment by Sangamesh-ts** [comment]
any update on this? is this being prioritized ?

**Comment by mirzaprangon** [comment]
I would also like support for gradle. Is there any plan on supporting gradle?

**Comment by IlonaShishov** [comment]
Hello,

Gradle support has been added in the latest release, version 0.9.5. We appreciate your help in improving the project. If you have any further issues or suggestions, please feel free to reach out.

Best regards.
