### ISSUE TITLE
Stop showing popups telling me everything is fine everytime I open a pom.xml/package.json

### ISSUE THREAD

**Issue by fbricon** [fabric8-analytics/fabric8-analytics-vscode-extension#434]
I'm always frustrated when an extension message pops up telling me everything is fine, every time I open a file.

This happens when opening pom.xml or package.json files:

<img width="470" alt="Screen Shot 2020-10-28 at 11 34 26 AM" src="https://user-images.githubusercontent.com/148698/97425062-e1e5bc00-1911-11eb-8929-e1e30be22bb0.png">

Only when a problem is detected should that popup appear. At the very least a don't show again option should be available

In 100% of the cases, having 0 dependencies should never pop up anything:
<img width="459" alt="Screen Shot 2020-10-28 at 11 43 15 AM" src="https://user-images.githubusercontent.com/148698/97425747-cb8c3000-1912-11eb-9e44-3f9b57545ebe.png">

**Comment by fbricon** [comment]
You might want to consider displaying something less conspicuous in the status bar instead (icon + [analysis in progress / X known vulnerabilities] on hover)

**Comment by arajkumar** [comment]
@fbricon , I agree on now showing the popup when there is no vulnerability. However if there is a vulnerability, we would like to show the popup at least once in the life time of workspace.

example:
- Open the project "foo" workspace
- Open pom.xml
    - Vulnerability popup will be shown
- Edit pom.xml
    - No popups
- Close pom.xml
- Open pom.xml (again)
    - No popups
- Close workspace

- Open the project "foo" workspace (again)
- Open pom.xml
    - Vulnerability popup will be shown
- Edit pom.xml
    - No popups
- Close pom.xml
- Open pom.xml (again)
    - No popups
- Close workspace

WDYT?

CC: @prashbnair

**Comment by fbricon** [comment]
Latest behavior is much better, so that's pretty cool. 

I think we can improve it a bit more though. 
<img width="225" alt="Screenshot 2020-12-18 at 09 29 15" src="https://user-images.githubusercontent.com/148698/102592568-ec535380-4113-11eb-95a3-91dc26b794e6.png">

- could use a ["safe" icon](https://www.google.com/search?q=safe+icon&tbm=isch&chips=q:safe+icon,g_1:transparent:xFy0n3aSa7o%3D&hl=en&sa=X&ved=2ahUKEwiboIHdj9ftAhUN-xoKHdv9A9QQ4lYoAHoECAEQGQ&biw=1514&bih=824).  
- OK status label is a bit too wordy IMHO. I'd remove it, if we use a self-explanatory icon. Else simply say "No known vulnerabilties". We don't really care about the number of scanned dependencies. If you really want to have it mentioned somewhere, just add it in the hover
- Be concise, without using abbreviations:
<img width="221" alt="Screenshot 2020-12-18 at 09 43 07" src="https://user-images.githubusercontent.com/148698/102593803-98e20500-4115-11eb-9044-e130b72e7596.png">
=> Found 8 vulnerabilities

**Comment by fbricon** [comment]
also "click here for Detailed Vulnerability Report" => "Open the detailed vulnerability report"

**Comment by arajkumar** [comment]
@fbricon Please check below texts. Is this okay?

<img width="156" alt="Screenshot 2020-12-18 at 3 18 52 PM" src="https://user-images.githubusercontent.com/3874763/102600075-58e64680-4144-11eb-92c9-470fc4450b50.png">
<img width="229" alt="Screenshot 2020-12-18 at 3 19 55 PM" src="https://user-images.githubusercontent.com/3874763/102600175-7ddab980-4144-11eb-9147-a49f3a32f6fc.png">
<img width="173" alt="Screenshot 2020-12-18 at 3 20 31 PM" src="https://user-images.githubusercontent.com/3874763/102600226-93e87a00-4144-11eb-8cd2-d1e17431a7af.png">

**Comment by fbricon** [comment]
1st two are ok for me
last one: simple tick icon is not enough on is own, thus requires the text. But we want to avoid bloating the status bar as much as possible. That's why I'd really like to see the safe icon only, if possible.

**Comment by arajkumar** [comment]
@fbricon I couldn't find a shield with tick emoji. Do you think just a shield emoji would work?

<img width="226" alt="Screenshot 2020-12-18 at 3 38 39 PM" src="https://user-images.githubusercontent.com/3874763/102602132-1bcf8380-4147-11eb-8ef9-ffcde0802cb6.png">

**Comment by arajkumar** [comment]
How about shield with check? Too weird?

<img width="41" alt="Screenshot 2020-12-18 at 3 41 28 PM" src="https://user-images.githubusercontent.com/3874763/102602409-81237480-4147-11eb-91f6-c58576fe80e1.png">

**Comment by fbricon** [comment]
I think shield+tick works

**Comment by maheshwari-git** [comment]
Shield with tick - looks neat !
