### ISSUE TITLE
[BUG] Extension overrides default keybinding for opening the debugger view

### ISSUE THREAD

**Issue by datho7561** [fabric8-analytics/fabric8-analytics-vscode-extension#442]
**Describe the bug**
The extension overrides the default keybinding for opening the debugger view (Ctrl+Shift+D)

**To Reproduce**
1. Install the extension
2. Press Ctrl+Shift+D

**Expected behavior**
Debugger view is displayed in the left panel

**Screenshots**
![DependencyAnalyticsExtension](https://user-images.githubusercontent.com/22376627/98693763-b239a980-233e-11eb-8f27-42c10d6c97f5.png)

**Logs**
Empty if I run it immediately after VS Code starts, but if I wait a bit before entering the keybinding I get this instead:

```
 CMD :npm --prefix="/home/dthompson/Documents/vscode-xml" install "/home/dthompson/Documents/vscode-xml" --quiet && npm list --prefix="/home/dthompson/Documents/vscode-xml" --prod -json > "/home/dthompson/Documents/vscode-xml/target/npmlist.json" --quiet
 STDOUT : 
> vscode-xml@0.14.0 preinstall /home/dthompson/Documents/vscode-xml
> npx npm-force-resolutions

audited 689 packages in 6.82s

4 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

 
 STDERR : npx: installed 5 in 1.789s
```

**VSCode(please complete the following information):**
 - OS: Fedora 33
 - VSCode version: 
   1.51.0
   fcac248b077b55bae4ba5bab613fd6e9156c2f0c
   x64
 - Dependency Analytics Version: 0.2.1

**CHE7/Theia(please complete the following information):**
I haven't tested in Theia or Che

**Additional context**

**Comment by fbricon** [comment]
We should definitely not override any built-in keybinding. I might be OK in a very well defined and restricted context though.
