### ISSUE TITLE
Cache reports and update in the background

### ISSUE THREAD

**Issue by fbricon** [fabric8-analytics/fabric8-analytics-vscode-extension#446]
Every time I click on the report icon, a new report is generated, which takes forever.

The generated report should be cached on disk, for a given effective-pom hash, for say 15 min. and simply be reopened when clicking on the icon.
When the time limit period is reached, instead of blindly evicting the cached report, it could still be displayed but a progress bar would show it's being updated behind the scenes. Then the page would update when completed and report actually changed.
You could let users configure the amount of cached reports (max X reports, or set an overall size limit)

**Comment by arajkumar** [comment]
Thanks @fbricon for your suggestion. Similar request has been already logged into our backlog., we will try to prioritise it.
  
https://issues.redhat.com/browse/APPAI-1381
