### ISSUE TITLE
[BUG] Output log opens everytime requirements.txt is opened

### ISSUE THREAD

**Issue by tristan957** [fabric8-analytics/fabric8-analytics-vscode-extension#458]
**Describe the bug**
The output window for Dependency Analytics takes focus and is opened every time I open my requirements.txt file. It is really breaking my workflow.

I think the reason the output window is being focused is because some of the requests it seems to try to make fail. I am behind a corporate VPN, but have my proxy settings set within my settings.json. This is just speculation.

**To Reproduce**
1. Create requirements.txt
2. Get into a position where network requests from Dependency Analytics will fail
3. Open requirements.txt after previously closing it
4. Notice output window now has focus

**Expected behavior**
Never focus the output window even when there are errors

**Screenshots**
![image](https://user-images.githubusercontent.com/11936772/101116953-a80c7300-35ab-11eb-8c36-0e26fe51ff4e.png)

**VSCode(please complete the following information):**
 - OS: Win 10 1909
 - VSCode version: 1.50
 - Dependency Analytics Version: 0.2.1

**Comment by prashbnair** [comment]
@arajkumar Maybe a flag to turn off CA when not required will be helpful?

**Comment by arajkumar** [comment]
@tristan957 Thanks for reporting this.

@prashbnair , it is due to the function which we use to log error. `connection.console.error` causes the output window focus, switching to `connection.log.warn` fixes the issue.

**Comment by tristan957** [comment]
Thanks for the quick fix!
