### ISSUE TITLE
[BUG] status bar icon tries to open a report for the currently opened file 

### ISSUE THREAD

**Issue by fbricon** [fabric8-analytics/fabric8-analytics-vscode-extension#478]
**Describe the bug**
Click on the status bar icon tries to open a report for the currently opened file 

**To Reproduce**
1. Open any file in VS Code (from a Maven or JS project)
2. Click on the :shield: icon in the status bar
3. Message pops up: 'File /whatever is not supported'

**Expected behavior**
The report from the current project's package.json (or whatever relevant build file) should be opened.

Alternatively, don't show the icon if the current file is not supported

**Screenshots**
<img width="813" alt="Screenshot 2021-01-06 at 12 12 23" src="https://user-images.githubusercontent.com/148698/103762573-cf29ea80-5018-11eb-93a6-5e46b26d94a4.png">

**VSCode(please complete the following information):**
 - OS: macOS 10.15.7
 - VSCode version 1.52.1
 - Dependency Analytics Version  0.3.0

**Comment by arajkumar** [comment]
Thanks @fbricon for reporting this. Indeed it is a bug and will be fixed soon.

**Comment by arajkumar** [comment]
@fbricon, 0.3.1 has the fix. Please give a try and let us know.
