### ISSUE TITLE
[BUG] creating workspace-logs\ls-bayesian\bayesian.log

### ISSUE THREAD

**Issue by tg123** [fabric8-analytics/fabric8-analytics-vscode-extension#496]
**Describe the bug**

the extension always created a file called
`workspace-logs\ls-bayesian\bayesian.log`

**To Reproduce**

open and close vscode

**Expected behavior**

No extra files

**Screenshots**

![image](https://user-images.githubusercontent.com/170430/108262978-7d49a980-711a-11eb-840d-5db7c847f4c2.png)

check
"~\.vscode\extensions\redhat.fabric8-analytics-0.3.2\dist\server.js"
![image](https://user-images.githubusercontent.com/170430/108263107-a8cc9400-711a-11eb-8c45-6213f0dc4bf3.png)

**Logs**
If applicable, attach logs.

**VSCode(please complete the following information):**
 - OS: [Windows]
 - VSCode version [e.g. 1.33.1]
 - Dependency Analytics Version [0.3.2]

**CHE7/Theia(please complete the following information):**
 - OS: [e.g. macOS]
 - Browser [e.g. chrome]
 - CHE/Theia version 
 - Dependency Analytics Version [0.3.2]

**Additional context**

**Comment by tg123** [comment]
seems this line @arajkumar 

https://github.com/fabric8-analytics/fabric8-analytics-lsp-server/blob/5a20da27966a1732f831b63afb2c6fc63a345213/src/server.ts#L29

**Comment by arajkumar** [comment]
Thanks @tg123 for reporting this.
