### ISSUE TITLE
Posibility to ignore warnings

### ISSUE THREAD

**Issue by os-tvv** [fabric8-analytics/fabric8-analytics-vscode-extension#501]
**Is your feature request related to a problem? Please describe.**
I have an old system with an even older dependency to an old package with no new versions to upgrade to. that solves the issue.
Current Version: 3.1
Recommended Version: N/A

**Describe the solution you'd like**
If I could ignore this dependency from the Dependency Analytics somehow. An settingsfile, or maybe a comment, like lint or equal

**Comment by IlonaShishov** [comment]
Ignoring dependencies available in latest version, please see documentation.
