### ISSUE TITLE
[BUG] go run github.com/fabric8-analytics/cli-tools/gomanifest doesn't work, but gomanifest itself does, and the extension is trying for go run ...

### ISSUE THREAD

**Issue by Ortega-Dan** [fabric8-analytics/fabric8-analytics-vscode-extension#504]
**Describe the bug**
Im not sure but I think it is that the extension doesn't work very well with golang 1.16, because of the following error I'm getting when trying to get the analysis for a golang project.

This is the ouput of the "Dependency Analytics" console:
```
 CMD :go get -u github.com/fabric8-analytics/cli-tools/gomanifest && go run github.com/fabric8-analytics/cli-tools/gomanifest "/home/user/testingProject/" "/home/user/testingProject/target/golist.json" "go"
 STDOUT :  
 STDERR : no required module provides package github.com/fabric8-analytics/cli-tools/gomanifest: go.mod file not found in current directory or any parent directory; see 'go help modules'
```

So the specific error seems to be that the command: go run github.com/fabric8-analytics/cli-tools/gomanifest is not runnable, since if I run the same command from an external terminal in a different directory it gives the same error, even when the command "gomanifest" alone works (meaning "gomanifest" is installed and found in the path).

**To Reproduce**
1. Ubuntu 20.04 and VScode downloaded and installed manually.
2. Just open a golang project, and from the go.mod file open, click on the 'Open Vulnerability Report' icon:
![image](https://user-images.githubusercontent.com/24926168/112878427-8caf0180-908d-11eb-9277-889b486ee568.png)
3. Te following notification appears, just click on "Show Output Log"
![image](https://user-images.githubusercontent.com/24926168/112878527-ad775700-908d-11eb-808c-15d426af38f0.png)

**VSCode(please complete the following information):**
 - OS: Ubuntu 20.04
 - VSCode version 1.54.3
 - Dependency Analytics Version 0.3.0

**Comment by Ortega-Dan** [comment]
After changing the command to run, directly from the installed extension file at ~/.vscode/extensions/redhat.fabric8-analytics-0.3.2/dist/extension.js ...
changing it to run "gomanifest", instead of "go run github.com/fabric8-analytics/cli-tools/gomanifest" it worked perfectly.

**Comment by dgpatelgit** [comment]
@Ortega-Dan I was looking into this issue, and thought of simplify this two step of getting module and than running it, into one step. 
I replace below code in extension.js:
`const h=[c.getGoExecutable(),"get","-u","github.com/fabric8-analytics/cli-tools/gomanifest","&&",c.getGoExecutable(),"run","github.com/fabric8-analytics/cli-tools/gomanifest",`"${u}"`,`"${m}"`,`"${c.getGoExecutable()}"`].join(" ");`

to 

`const h=[c.getGoExecutable(),"run","github.com/fabric8-analytics/cli-tools/gomanifest",`"${u}"`,`"${m}"`,`"${c.getGoExecutable()}"`].join(" ");`

Which worked for me during testing. Could you also confirm this modification once? (before I make a real PR)

**Comment by Ortega-Dan** [comment]
Thanks for the response @dgpatelgit

Unfortunately it didn't work. I installed the VSIX extension and it is reporting the following:

I believe it is something related with GO111MODULE in Golang 1.16 ... according to: https://blog.golang.org/go116-module-changes

The following is the error (with the VSIX extension provided), when GO111MODULE=off
![image](https://user-images.githubusercontent.com/24926168/114430529-25607980-9b84-11eb-97d3-feffbc3e67f6.png)
(Invalid arguments)

And with GO111MODULE=on, the following error.
![image](https://user-images.githubusercontent.com/24926168/114431039-acaded00-9b84-11eb-9975-aeaca67e512b.png)
(No required module provides package)

**Comment by Ortega-Dan** [comment]
The thing is that the default config is GO111MODULE not set (or GO111MODULE=on)

**Comment by Ortega-Dan** [comment]
I propose PR #508 It works for Windows and Linux.

**Comment by dgpatelgit** [comment]
@Ortega-Dan I will look at PR and suggestion you made.

**Comment by Ortega-Dan** [comment]
@dgpatelgit The commit already on master works very well. Thanks. But it didn't work on Windows. Then I just created PR #510 which adds upon your fix and includes Windows support.

**Comment by rafaribe** [comment]
This is also happening to me on MacOS.
