### ISSUE TITLE
Ignore unparseable files from telemetry reporting

### ISSUE THREAD

**Issue by fbricon** [fabric8-analytics/fabric8-analytics-vscode-extension#513]
**Is your feature request related to a problem? Please describe.**
Any package.json file being edited that breaks the json format still triggers dependency analysis. Analysis fails because of the malformed document but is reported in Woopra, which adds no value because it's not actionable, eg:

```
component_analysis_failed, error:
column=44&line=8&message=Unexpected symbol <c> at 8:44 6 | "scripts": { 7 | "test": "echo \"Error: no test specified\" && exit 1", 8 | "deploy": "serverless deploy -s, ^ 9 | "create:domain": "serverless create_domain -s", 10 | "start:offline": "serverless offline --skipCacheInvalidation start -s"&name=SyntaxError&rawMessage=Unexpected symbol <c> at 8:44&source= 
```

Moreover these eat our Woopra action quota.

**Describe the solution you'd like**
Unless there's value in reporting such events (please enlighten me), please ignore syntax errors from reporting, so we can focus on real errors.

**Comment by arajkumar** [comment]
@fbricon , yes. this should be ignored.
