### ISSUE TITLE
[BUG] Link to Release Notes not working because of missing Github release.

### ISSUE THREAD

**Issue by ringods** [fabric8-analytics/fabric8-analytics-vscode-extension#523]
**Describe the bug**
After update of the extension, the **Release Notes** button in the extension notification points to a non-existing location on Github (404)

**To Reproduce**
1. Have VSCode with an older version of the extension
2. Let it update
3. See the notification in the bottom right with **Readme** and **Release Notes** buttons.
4. Click on **Release Notes**
5. Browser is pointed to this URL which gives a 404: https://github.com/fabric8-analytics/fabric8-analytics-vscode-extension/releases/tag/0.3.3

**Expected behavior**

The link should work, but there are no Github releases beyond v0.3.1:

https://github.com/fabric8-analytics/fabric8-analytics-vscode-extension/releases

**Comment by arajkumar** [comment]
Thanks for reporting. Unfortunately the GH release publishing is not automated. Just fixed it.

https://github.com/fabric8-analytics/fabric8-analytics-vscode-extension/releases/tag/0.3.3
