### ISSUE TITLE
On unauthorization, multiple markers appear.

### ISSUE THREAD

**Issue by GeetikaBatra** [fabric8-analytics/fabric8-analytics-vscode-extension#53]
`Authorize to OSIO ` appears multiple times when user  unauthorizes repeatedly.

<img width="1680" alt="screen shot 2018-01-05 at 12 25 52 pm" src="https://user-images.githubusercontent.com/8664238/34599101-b61437a2-f216-11e7-9655-7221899a622e.png">

  

Version - 1.19

**Comment by invincibleJai** [comment]
this PR should fix https://github.com/fabric8-analytics/vscode-osio-auth/pull/26

**Comment by invincibleJai** [comment]
fixed
