### ISSUE TITLE
[BUG] npm install inside vscode folder rather than workspace

### ISSUE THREAD

**Issue by Fydon** [fabric8-analytics/fabric8-analytics-vscode-extension#538]
**Describe the bug**
The Stack Report is failing as VS Code is installed in Program Files, I'm not running it as Administrator and npm install is trying to create C:\Program Files\Microsoft VS Code Insiders\node_modules.

**To Reproduce**
1. Install VS Code in Program Files
2. Run Stack Report

**Expected behavior**
npm command would run using the workspace folder's path

**Logs**
[2021-08-25T09_50_07_415Z-debug.log](https://github.com/fabric8-analytics/fabric8-analytics-vscode-extension/files/7046008/2021-08-25T09_50_07_415Z-debug.log)

**VSCode(please complete the following information):**
 - OS: Windows 10
 - VSCode version 1.60.0-insider (system setup)
   Commit: 5f19eee5dc9588ca96192f89587b5878b7d7180d
   Date: 2021-08-24T19:41:58.784Z
 - Dependency Analytics Version 0.3.3

**Comment by Luxiorawa** [comment]
Any news on this ? bug still occuring...

**Comment by Groovin-Dev** [comment]
Still happening as of 4/26/2023 with version 0.3.6

**Comment by IlonaShishov** [comment]
According to the logs provided this seems like a Permissions issue.
Closing this issue due to it being outdated and relevant to old and irrelevant versions of this plugin.
please reopen if bug persists for the latest plugin version.
