### ISSUE TITLE
Size of extension is huge like 94MB

### ISSUE THREAD

**Issue by invincibleJai** [fabric8-analytics/fabric8-analytics-vscode-extension#54]

**Comment by krishnapaparaju** [comment]
@invincibleJai Does this size include both Auth and Analytics extensions ?

**Comment by invincibleJai** [comment]
@krishnapaparaju Auth one is 20 MB and f8 analytics is 94MB, am doubting readme images https://github.com/fabric8-analytics/fabric8-analytics-vscode-extension need to try

**Comment by invincibleJai** [comment]
@krishnapaparaju issue with size is fixed in this PR https://github.com/fabric8-analytics/fabric8-analytics-vscode-extension/pull/55, now it's 3.2 MB for f8-analytics

**Comment by invincibleJai** [comment]
fixed
