### ISSUE TITLE
[BUG] This extension causes VSCode Jupyter Notebook to malfunction

### ISSUE THREAD

**Issue by abceleung** [fabric8-analytics/fabric8-analytics-vscode-extension#546]
**Describe the bug**
With this extension and the VSCode Python extension (with all its dependencies) enabled, jupyter notebook files not longer have highlighted syntax and debug function. 
Removing this extension restores the intended behavior.

**To Reproduce**
1. With a clean install of VSCode, install the Python extension.
2. Open a Jupyter Notebook file (.ipynb), Python syntax should be highlighted and you can debug (e.g. set breakpoints).
3. Install the Dependency Analytics extension and reload VSCode
4. Now the language of the notebook cells becomes "CVE" and Python features no longer work. 

**Expected behavior**
Python features inside Jupyter Notebooks should work normally even with this extension installed.

**Screenshots**
Dependency Analytics disabled:
![image](https://user-images.githubusercontent.com/82202780/136729492-01b5cdbc-2f2e-4622-a92f-48732c5bc945.png)
Dependency Analytics enabled (and VSCode reloaded):
![image](https://user-images.githubusercontent.com/82202780/136729598-d162148d-c866-4dac-bcb8-692dab9787b5.png)

**VSCode(please complete the following information):**
 - OS: Windows 10 
 - VSCode version: 1.61.0
 - Dependency Analytics Version: v0.3.4
 - Jupyter extension version: v2021.9.1001312534

**Comment by DonJayamanne** [comment]
Hi I'm one of the engineers from the VS Code & Jupyter extension.
I've had a look at the code, and unable to determine why we need an alias for the `python` language. 
I'm referring the the `python` entry in the following section of `package.json`
```jsonc
      {
        "id": "security",
        "aliases": [
          "CVE",
          "python",
          "pom.xml",
          "package.json",
          "requirements.txt"
        ]
      },
```

**Comment by SaurabhAware** [comment]
Uninstalled it ... and problem is gone. Thanks..!

**Comment by jparsai** [comment]
Apologies for the delay in fixing this issue. It is resolved in https://github.com/fabric8-analytics/fabric8-analytics-vscode-extension/pull/570. 
0.3.6 version of extension is published for this fix. Feel free to reopen issue, if it still exists.
