### ISSUE TITLE
Dependency Analytics  conflict with jupyter

### ISSUE THREAD

**Issue by Kurt-Shiwz** [fabric8-analytics/fabric8-analytics-vscode-extension#547]
- VS Code Version: 1.61.0
- OS Version: mac 11.6
- python: v2021.10.1317843341
- pylance: v2021.10.0
- jupyter: v2021.9.1001312534
- `Dependency Analytics: v0.3.4`

when i install `Dependency Analytics` open jupyter file `a.ipynb`,  code python in `Cell` cant auto complete and cant use some hotkey(cmd + / ) in cell.  code python in `b.py` it work well.
when i disable `Dependency Analytics` jupyter work well.

**Comment by qxdn** [comment]
+1

**Comment by sleepymalc** [comment]
Thanks for bisect, I encounter the same issue.

**Comment by comphsics** [comment]
the same problem

**Comment by cmsax** [comment]
same issue, cause vscode ipynb jupyter notebook intellisense not working.

**Comment by josephmcg16** [comment]
Still have the same issue.

**Comment by systematiccaos** [comment]
+1

**Comment by systematiccaos** [comment]
Maybe you might close this issue, now that it's fixed too. :-)

**Comment by jparsai** [comment]
Thanks @systematiccaos for fixing this issue :).
Apologies for the delay.
0.3.6 version of extension is published for this fix. Feel free to reopen issue, if it still exists.
