### ISSUE TITLE
Update CRDA extension icon in VSCode Marketplace

### ISSUE THREAD

**Issue by mohitsuman** [fabric8-analytics/fabric8-analytics-vscode-extension#549]
**Is your feature request related to a problem? Please describe.**

Currently the [CRDA extension](https://marketplace.visualstudio.com/items?itemName=redhat.fabric8-analytics) uses the OpenShift icon in VSCode Marketplace. Given there are too many OpenShift icon extensions, we need to define each extension with an exclusive icon for it.

**Describe the solution you'd like**

For now, we can use a custom icon (needs to be defined) and replace the OpenShift icon. This can go out with the next release for CRDA.

**Comment by IlonaShishov** [comment]
Icon has been updated
