### ISSUE TITLE
Don't reload stack report on tab change in VS code

### ISSUE THREAD

**Issue by abs51295** [fabric8-analytics/fabric8-analytics-vscode-extension#56]
Currently, stack report is reloaded for the same stack when the user navigates away and then comes back to the stack report tab. It would be better if we can cache the result and not reload it every time for this scenario.

**Comment by sivaavkd** [comment]
+1

**Comment by invincibleJai** [comment]
closing as dup of https://github.com/fabric8-analytics/fabric8-analytics-vscode-extension/issues/89
