### ISSUE TITLE
Extension causes python syntax to change to CVE

### ISSUE THREAD

**Issue by dacort** [fabric8-analytics/fabric8-analytics-vscode-extension#567]
Issue Type: <b>Bug</b>

- Open a new document.
- Either click on "Select a language" or click on "Plain Text" in the lower right-hand corner to change the document language.
- Select "Python"
- Expected result: Python language is selected in the lower right and syntax highlighting is correct
- Actual result: CVE language is selected! 😮 

Extension version: 0.3.5
VS Code version: Code 1.65.0 (b5205cc8eb4fbaa726835538cd82372cc0222d43, 2022-03-02T11:11:20.886Z)
OS version: Darwin x64 21.3.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8569U CPU @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (0.35GB free)|
|Process Argv|--crash-reporter-id ce25b33f-c42e-49fc-94ea-ee281b74dbec|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by jparsai** [comment]
Apologies for the delay in fixing this issue. It is resolved and 0.3.6 version of extension is published for this fix. Feel free to reopen issue, if it still exists.
