### ISSUE TITLE
[BUG] Can't create any analytics report

### ISSUE THREAD

**Issue by theit** [fabric8-analytics/fabric8-analytics-vscode-extension#568]
**Describe the bug**
Trying to create a dependency analytics report always results in an error page: "Unable to analyze your stack."

**To Reproduce**
1. Open a (Maven) project in VS Code
2. Right-click on the `pom.xml` or `package.json` file
3. Choose "Dependency Analytics Report..." from the popup menu.
4. An error page with the above mentioned message is shown.

**Expected behavior**
The report is generated as described in the wiki page.

**Logs**
In ~/AppData/Roaming/Code/logs/20220329T162957/exthost1/output_logging_20220329T163000 I found the following in the file `4-Dependency Analytics.log` when I tried to create the report on a `pom.xml`:
```
 CMD :"mvnd.exe" --quiet clean -f ".....\ui\pom.xml" && "mvnd.exe" --quiet org.apache.maven.plugins:maven-dependency-plugin:3.0.2:tree -f ".....\ui\pom.xml" -DoutputFile=".....\ui\target\dependencies.txt" -DoutputType=dot -DappendOutput=true
 STDOUT :
 STDERR :
```
(I'm using https://github.com/apache/maven-mvnd instead of "plain" Maven (3.8.5), but even with Maven 3.8.5 the output is the same).

and similar for `package.json`:
```
 CMD :npm install ".....\ui" --quiet && npm list --prefix=".....\ui" --prod -json > ".....\ui\target\npmlist.json" --quiet
 STDOUT :
up to date, audited 3 packages in 1s

found 0 vulnerabilities

 STDERR :
```
Note: Both output files (dependencies.txt and npmlist.json) are generated in the project's target folder and contain data.

**VSCode**
 - OS: Windows 10 Enterprise, Version 10.0.19044 Build 19044
 - VSCode version: 1.65.2
 - Dependency Analytics Version: v0.3.5

**Additional context**
I'm using VSCode from within a company network that has its own proxy and root CA. My first guess was the plugin has problems using the proxy, but because a) I have configured environment variables "http_proxy" and "https_proxy" and b) VSCode can install extensions from the market place, this shouldn't be the case. Apart from that changing the proxy settings in VSCode ("http.proxy", "http.proxyStrictSSL" and "http.proxySupport") doesn't have any effect...

**Comment by jorge683** [comment]
I have the same problem :(
