### ISSUE TITLE
[BUG] Can't create Python analytics report 

### ISSUE THREAD

**Issue by LeMoussel** [fabric8-analytics/fabric8-analytics-vscode-extension#583]
**Describe the bug**
Trying to create a Python dependency analytics report always results error : `command 'fabric8.stackAnalysisFromPieBtn' not found`.

**To Reproduce**
1. Open a Python project in VS Code
2. Load `requirements.txt` file in editor
3. Click on 'Open Vulnerability Report'
4. Error with the above mentioned message is shown.

**Expected behavior**
The report is generated as described in the wiki page.

**Screenshots**
![image](https://user-images.githubusercontent.com/1816573/176372173-6f325284-2205-4803-8a3d-8997855717e0.png)

**VSCode**
 - OS: Windows 10 Enterprise, Version Windows_NT x64 10.0.19044
 - VSCode version 1.68.1 
   - Electron : 17.4.7
   - Chromium: 98.0.4758.141
   - Node.js : 16.13.0
   - V8 : 9.8.177.13-electron.0
 - Dependency Analytics Version 0.3.6

**Additional context**
I'm using VSCode from within a company network that has its own proxy.

**Comment by PStoner3** [comment]
This is not just isolated to python projects. I am experiencing the same issues with golang and maven projects.

I'm experiencing the issue v0.3.6 of the extension. My vs code information is:
Version: 1.70.0 (user setup)
Commit: da76f93349a72022ca4670c1b84860304616aaa2
Date: 2022-08-04T04:38:16.462Z
Electron: 18.3.5
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Windows_NT x64 10.0.19041

**Comment by gian1200** [comment]
I'm also facing the same issue on some java projects with maven. (actually, it has been a few months).
It works after restarting VSCode between 1 and several times. (it sometimes requires to also delete the `target` folder).
I also noticed that the extension usually doesn't work when the app/project is running
