### ISSUE TITLE
set vulnerability as warn, not error

### ISSUE THREAD

**Issue by quinnInChina** [fabric8-analytics/fabric8-analytics-vscode-extension#597]
**Is your feature request related to a problem? Please describe.**
when there is a vulnerability in the pom.xml, the extension will set it as an error to vscode java ide. and you will see red color on the file name, and error problem in Problems tab.
like this:
![image](https://user-images.githubusercontent.com/2950260/206947118-42d45e13-039a-454e-ad0f-23cb5e57e478.png)

but, this vulnerability doesnot affect my project, and i dont need fix it!
in general, when there are red or error, means we must fix it, so i think its conflict.

**Describe the solution you'd like**
i suggest, there is a config for developers to set it is error or warn when vulnerabilities have been detected

not ignore it by `<!--crdaignore-->`

**Comment by IlonaShishov** [comment]
Hello @quinnInChina ,
Thank you for pointing this out, 
we have discussed this matter with the team and we will be adding a setting to the future version of our plugin that will allow the user to define the severity level of the RHDA Dependency vulnerability alerts, either Error or Warning.
