### ISSUE TITLE
About the notice

### ISSUE THREAD

**Issue by Carson-yy** [fabric8-analytics/fabric8-analytics-vscode-extension#605]
![image](https://user-images.githubusercontent.com/12856549/218416588-1dadf190-8bc3-4599-84af-5e52bbacb5eb.png)

It will notify multiple times when multiple items are opened.

Can you set no notification?

**Comment by IlonaShishov** [comment]
Hi @Carson-yy ,
Thanks for reaching out,
you have a built in feature for this in VSCode. 
"Do Not Disturb" mode hides all non-error notification pop-ups, that means error notification pop-ups will still appear.
To turn off notifications, go to the bottom right side of the app, click the bell icon and then click the other bell icon to toggle the Do Not Disturb option.
