### ISSUE TITLE
Improve On-click stack-report sentence

### ISSUE THREAD

**Issue by sara-02** [fabric8-analytics/fabric8-analytics-vscode-extension#61]
A minor suggestion:
Instead of saying `Generate fabric8-analytics stack report` and `Generate fabric8-analytics stack report on Workspace `
we can be more specific by saying `Generate fabric8-analytics stack report for the pom` and `Generate fabric8-analytics stack report for the workspace`

![screenshot from 2018-01-18 13-03-55](https://user-images.githubusercontent.com/7047079/35085868-72d63fc8-fc50-11e7-84f5-2557b179bd38.png)

**Comment by invincibleJai** [comment]
two separate commands are merged into one and has been reworded
