### ISSUE TITLE
Allow moving .redhat directory to conform with XDG Base Dirs

### ISSUE THREAD

**Issue by torjacob** [fabric8-analytics/fabric8-analytics-vscode-extension#611]
**Is your feature request related to a problem? Please describe.**
At current, the __/.redhat__ directory is generated in __$HOME__ whenever running Vscode with the extension enabled. This clutters the home directory, in addition to not giving a clear indication of what type of data is to be expected in this folder (e.g. cahce/userdata/etc.). In essence, it breaks consistency.

**Describe the solution you'd like**
I would like to be able to move this directory to comply with the [XDG Base Dir spec.][xdg] Either through setting it as a default, or giving an option / environment variable.
If files are generated on future runs, I would like them to appear/be read from that location.

**Describe alternatives you've considered**
I have considered symlinking the folder with __$XDG_DATA_DIRECTORY__/redhat, which functions as a stopgap - however this does not really accomplish the main goal of keeping the __$HOME__ directory tidy/consistent.

**Additional context**
This issue has been reproduced both with wsl2 (VScode-server), and VScode on 'native' Linux.

**XDG Base Directory Specification (summary)**
| Environment Variable | Data to be stored in location    | Fallback if not set |
|----------------------|----------------------------------|---------------------|
| $XDG_DATA_HOME       | User-specific data files         | $HOME/.local/share  |
| $XDG_CONFIG_HOME     | User-specific config files       | $HOME/.config/      |
| $XDG_STATE_HOME      | User-specific state files        | $HOME/.local/state  |
| $XDG_CACHE_HOME      | User-specific non-essential data | $HOME/.cache        |

For the complete specification, see [here][xdg].

[xdg]: https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html

**Comment by TomerFi** [comment]
Hi @torjacob 

The **.redhat** folder is shared with Red Hat telemetry extension. More specifically, this folder contains a file named _anonymousId_ containing a random uid used to identify telemetry tracking.

https://github.com/redhat-developer/vscode-redhat-telemetry/blob/main/src/webworker/vfsIdManager.ts#L39
