### ISSUE TITLE
Effective POM generation should not fail when there are multiple folders open in the same workspace.

### ISSUE THREAD

**Issue by rootAvish** [fabric8-analytics/fabric8-analytics-vscode-extension#62]
<img width="1680" alt="screen shot 2018-01-18 at 2 17 45 pm" src="https://user-images.githubusercontent.com/5445560/35088940-60f84e6c-fc5b-11e7-8d51-2da21844f403.png">

**Comment by invincibleJai** [comment]
@rootAvish thanks, currently multi level workspace is not supported. We'll be supporting it soon

**Comment by invincibleJai** [comment]
Closing as mutiroot support has been enabled
