### ISSUE TITLE
Extension fails to publish on Visual Studio Marketplace due to unsupported .svg

### ISSUE THREAD

**Issue by fbricon** [fabric8-analytics/fabric8-analytics-vscode-extension#624]
> Error processing 'redhat.fabric8-analytics' SVG reference in file '/extension/README.md'. Your reference to the SVG image ‘https://vsmarketplacebadge.apphb.com/version/redhat.fabric8-analytics.svg’ is not supported. Please see https://aka.ms/vsmarketplace_badge for more details.

https://github.com/fabric8-analytics/fabric8-analytics-vscode-extension/blob/4091bc8088ebe74aa77ff51eca3bdab411b1048c/README.md?plain=1#L3

**Comment by fbricon** [comment]
Extension is stuck at 0.3.6 on the marketplace, instead of 0.3.9

**Comment by TomerFi** [comment]
Thank you very much!
I don't have access to our marketplace account so I can't see this.
I just sent Ondrej a message about this, you were next in my list. 😁
