### ISSUE TITLE
Number of manifest files on workspace !== Number of tabs on the stack report UI

### ISSUE THREAD

**Issue by jyasveer** [fabric8-analytics/fabric8-analytics-vscode-extension#63]
PFA the screenshot
<img width="1440" alt="screen shot 2018-01-18 at 2 26 55 pm" src="https://user-images.githubusercontent.com/5430080/35089063-ceba3c58-fc5b-11e7-83fa-718c802ef22e.png">

**Comment by sanketpathak** [comment]
+1
 I'm also getting 5 tabs in stack report for 4 manifest files.

**Comment by invincibleJai** [comment]
this PR should fix it https://github.com/fabric8-analytics/fabric8-analytics-vscode-extension/pull/94
