### ISSUE TITLE
[BUG] The release notes button for the "dependency has been updated popup" is linking to a nonexistent tag

### ISSUE THREAD

**Issue by FieteO** [fabric8-analytics/fabric8-analytics-vscode-extension#648]
**Describe the bug**
The release notes button in the popup that is appearing after updating the dependency (to `0.7.0`) is linking to
`https://github.com/fabric8-analytics/fabric8-analytics-vscode-extension/releases/tag/0.7.0` instead of the correct
`https://github.com/fabric8-analytics/fabric8-analytics-vscode-extension/releases/tag/v0.7.0` (notice the `v` prefix)

The relevant line of code is [here](https://github.com/fabric8-analytics/fabric8-analytics-vscode-extension/blob/32ae923478b205b87faa95a0acaa93e7efb53949/src/extension.ts#L217):
```ts
await vscode.commands.executeCommand('vscode.open', vscode.Uri.parse(`${packageJSON.repository.url}/releases/tag/${version}`));
```
with the `version` taken from the [package.json](https://github.com/fabric8-analytics/fabric8-analytics-vscode-extension/blob/32ae923478b205b87faa95a0acaa93e7efb53949/package.json#L5), which is `0.7.0` (and not `v0.7.0`).
I don't know whats the best solution here, but I guess a quick fix would be to rename the git tag from `v0.7.0` to `0.7.0` to fix the link.

**Comment by IlonaShishov** [comment]
Thank you for reporting this issues,
fixed in version 0.9.0 and up.
