### ISSUE TITLE
Click on tabs in the stack report does not select the security card by default

### ISSUE THREAD

**Issue by jyasveer** [fabric8-analytics/fabric8-analytics-vscode-extension#65]
PFA the screenshot
<img width="1440" alt="screen shot 2018-01-18 at 2 35 34 pm" src="https://user-images.githubusercontent.com/5430080/35089412-e2488436-fc5c-11e7-81b0-71305672347a.png">

**Comment by arunkumars08** [comment]
Duplicate of https://github.com/fabric8-analytics/fabric8-analytics-vscode-extension/issues/68

**Comment by arunkumars08** [comment]
Fixed
