### ISSUE TITLE
[BUG] Can't generate Vulnerability Report due to Windows user folder containing space character

### ISSUE THREAD

**Issue by Ivo-Andrade-Taxation-Mind** [fabric8-analytics/fabric8-analytics-vscode-extension#657]
**Describe the bug**
The extension does not produce a vulnerability report for Windows users when their personal folder name (C:\Users\<User>) contain a space character in it (such as 'Name Surname').

**To Reproduce**
- Create a Windows user named 'Name Surname'
- Download and install VSCode
- Install both 'Extension Pack for Java' and 'Red Hat Dependency Analytics' extensions
- Create a new Maven Project (as seen in [VSCode's documentation](https://code.visualstudio.com/docs/java/java-build#_generate-project-from-maven-archetype)).
- When the user clicks 'Open Vulnerability Report', a new tab opens but it results in a blank page with the text Unable to analyze your stack., along with an extension error: Command failed: mvn -q clean -f c:\Users\Name Surname\Documents\demo\pom.xml.
- *Obs.:* When the process is performed for a Windows user named 'Name', the extension produces a report as expected.

**Expected behavior**
It's expected for the extension to produce a Vulnerability Report.

**VSCode(please complete the following information):**
Version: 1.84.1 (user setup)
Commit: 2b35e1e6d88f1ce073683991d1eff5284a32690f
Date: 2023-11-06T12:35:59.022Z
Electron: 25.9.2
ElectronBuildId: 24603566
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.22621
Dependency Analytics Version 0.7.3

**Comment by zvigrinberg** [comment]
@IlonaShishov kindly bump the version of exhort-javascript-api to v0.1.1-ea.13 in order to eliminate bug.
will be included in the next release.
