### ISSUE TITLE
Invalid purl: "versions" argument must be a string.

### ISSUE THREAD

**Issue by brayandiazssjd** [fabric8-analytics/fabric8-analytics-vscode-extension#664]
**Describe the bug**
I installed the extension and a notification says "Component Analysis error. Error: Invalid purl: "versions" argument must be a string.". The program work, but that notification makes me feel nervous XD
**To Reproduce**
I just made a regular installation from the manket place of the extensions.

**VSCode(please complete the following information):**
 - OS: Windows 10
 - VSCode version 1.85.0
 - Dependency Analytics Version 0.7.3
 - Maven version 3.9.5

**Comment by IlonaShishov** [comment]
Hello @brayandiazssjd ,
Thank you for reaching out,
In order to investigate this issue could you please provide the pom.xml you are having issues with and/or the full detailed logs for this issue?

**Comment by brayandiazssjd** [comment]
Omg sorry 😔, the 'error' stopped appearing days later 😄.
