### ISSUE TITLE
[BUG] maven.executable.path not used anymore

### ISSUE THREAD

**Issue by rubensa** [fabric8-analytics/fabric8-analytics-vscode-extension#665]
**Describe the bug**
[This](https://github.com/fabric8-analytics/fabric8-analytics-vscode-extension/commit/6c182a46cf6bf46f3461c9839c66c99d68557cdd#diff-c3095d5010e65c52737a98a5d618ea24049ebe90c8470752426081d70ed6e012) commit replaced `maven.executable.path` with `mvn.executable.path`, probably by mistake as `maven.executable.path` is the one used by the [VSCode Maven extension](https://github.com/Microsoft/vscode-maven#settings).

**To Reproduce**
1. Without maven globally installed
2. Set `maven.executable.path` in Settings
3. Open **pom.xml** and click **Open Vulnerability Report** icon

**Expected behavior**
The `maven.executable.path` setting is respected.

**Logs**
```bash
/bin/sh: 1: mvn: not found
manifest parse took 43 ms, found 13 deps
[Warn  - 8:05:45 AM] Component Analysis error. Error: Command failed: mvn --version
/bin/sh: 1: mvn: not found

fetch vulns took 5 ms
```

**VSCode(please complete the following information):**
 - OS: Ubuntu 22.04
 - VSCode version 1.85.0
 - Dependency Analytics Version 0.7.3

**Additional context**
As a workaround you can set both `mvn.executable.path` and `maven.executable.path` settings but that is not the expected behavior.

**Comment by rubensa** [comment]
Looks like the setting name [changed again](https://github.com/fabric8-analytics/fabric8-analytics-vscode-extension/blob/629d4c6b63ee463d362d6d4bf256d6c256a73631/package.json#L205).

Now changed from `mvn.executable.path` to `redHatDependencyAnalytics.mvn.executable.path`.

So, from now on, looks like the configuration properties are now specific for the extension under the `redHatDependencyAnalytics`base key (vs. reuse default configuration properties from other standard extensions).

_NOTE_:  To me, this kind of changes might be considered "breaking changes", but they are not even mentioned in the release notes.

**Comment by IlonaShishov** [comment]
Hi @rubensa  , 

Thanks for reaching out. 
Our recent changes intentionally differentiate our extension settings from other ones that are not related or unsupported by RedHat, like the Microsoft vscode-maven extension you have mentioned. This separation ensures our settings don't impact other extensions functionality, maintaining the unique semantic meaning of our settings. Our Maven path setting specifically serves our Exhort Analysis context.

We appreciate your input on this, could you please elaborate more on why you feel the need for shared extension settings? Understanding your perspective will help us better address user preferences and needs.

**Comment by rubensa** [comment]
Hi @IlonaShishov 

Thanks for your comment.

This is how a see the thing...

If you work with [Maven](https://maven.apache.org/) in [VSCode](https://code.visualstudio.com/) it is more than probable that you use the Microsoft [Maven for Java](https://marketplace.visualstudio.com/items?itemName=vscjava.vscode-maven) extension as is the one that appears in the [VSCode documentation](https://code.visualstudio.com/docs/java/java-build#_maven).

That said, if you configure the **maven** setting in VSCode you expect those configs to be taken into account by any extension using Maven in VSCode (so you do not have to configure same things multiple times).

For example, if this extension would also support the [Maven Wrapper](https://maven.apache.org/wrapper/) I would expect this to respect the value for `maven.executable.preferMavenWrapper` setting.

My suggestion:

- Keep a specific configuration for the extension (`redHatDependencyAnalytics.mvn.executable.path`)
- If not set, go for the "standard" configuration (`maven.executable.path`)
- If not set, got for the default value (' mvn' executable command)

This way, you are able to set an extension specific setting (just in case you don't want to affect others in VSCode) but you are not forced to use it (so use the default "standard" one, if set) and you also have a fallback when there is no setting.

**Comment by IlonaShishov** [comment]
@rubensa Thank you for the detailed explanation, 
it is very helpful to the team to include the users perspective when making adjustments to our plugin.
Your suggested solution will be considered by the team for future plugin updates. However, we appreciate your patience as this may require some time due to several factors to take into consideration related to our plans for the plugin's future versions.

**Comment by harshrathod50** [comment]
I do not have Maven globally installed and I'm getting this error:
```
Command failed: mvn --version 'mvn' is not recognized as an internal or external command, operable program or batch file.
```
So as a workaround I added did this in `settings.json`:
```json
{
  "redHatDependencyAnalytics.mvn.executable.path": "./mvnw"
}
```
But then I got this error:
```
Command failed: ./mvnw --version '.' is not recognized as an internal or external command, operable program or batch file.
```
So as a second workaround I did this:
```json
{
  "redHatDependencyAnalytics.mvn.executable.path": "%USERPROFILE%\\.m2\\wrapper\\dists\\apache-maven-3.9.5-bin\\32db9c34\\apache-maven-3.9.5\\bin\\mvn"
}
```
Which worked well but now this doesn't work on linux, so as a third workaround I did this:
```json
{
  "redHatDependencyAnalytics.mvn.executable.path": "$HOME/.m2/wrapper/dists/apache-maven-3.9.5-bin/32db9c34/apache-maven-3.9.5/bin/mvn"
}
```
Which worked well on linux but now this doesn't work on windows.
And then I gave up and removed RedHat Dependency Analytics extension. I just have two questions for the project maintainers:
* Why there is, no nonsense, no brainer, default support for Maven Wrapper?
* Why are you making life difficult then it already is?

**Comment by IlonaShishov** [comment]
Thank you again for reaching out and suggesting this feature to be reinstated.

After careful consideration and evaluation of our project's roadmap and priorities, we've decided not to support this feature at this time. However, we've noted your suggestion, and we'll keep it in mind for future iterations of the project.

If you have any other ideas or feedback, please don't hesitate to share them with us. We're always open to suggestions from our community.
