### ISSUE TITLE
maven project with parent-pom maybe have problem 

### ISSUE THREAD

**Issue by shangweikun** [fabric8-analytics/fabric8-analytics-vscode-extension#667]
I try to use this plugin,but it has an error 

Component Analysis error. Error: Command failed: mvn -q help:effective-pom -Doutput=${tmpPath}/effective-pom.xml -f ${tmpPath}/target-pom.xml

I have a project with three submodules underneath. The current error is being shown as this. Could it be because the issues with the submodules were not taken into consideration?

```console
[ERROR]   
[ERROR]   The project ${myProject}:1.0.0-SNAPSHOT (${tmpPath}/target-pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM for ${myProject-core}:1.0.0-SNAPSHOT Could not find artifact ${myProject}:1.0.0-SNAPSHOT and 'parent.relativePath' points at wrong local POM @ line 4, column 10 -> [Help 2]
```

**Comment by IlonaShishov** [comment]
Thank you for reaching out to us on this issue, 
We will examine this matter and address it in upcoming versions.
