### ISSUE TITLE
[BUG] Still maintained? Please fix annoying error notification on NodeJS project

### ISSUE THREAD

**Issue by CallMeLaNN** [fabric8-analytics/fabric8-analytics-vscode-extension#669]
**Describe the bug**
It is too annoying to see popup error notice many times recently from an analysis tool! waited for month(s) maybe but still exist. It supposed to silent or less brutal to warn developer. I got this recently since new update, probably related to other complains here also.

Does this project still maintained? Not much issue reply and only bump versions to have a good "Latest update" figure.

I'm not sure if you only support `npm` but NodeJS package manager quite competitive. You supposed to silent or not activate if `pnpm` is not supported.

The problem is I'm being using `pnpm` and having this extension installed for long time but the annoying error just happened recently.

**To Reproduce**
A. Load a NodeJS project in a VS Code, the error appear.
B. Try to add/remove a package from npm using pnpm, the error appear.
C. Switch branch, the error appear.
D. rm -rf node_modules and reinstall all. The error appear.
x. A few other ways that change the packages

**Expected behavior**
It supposed to silent or less brutal to warn developer. It supposed to disable if the project is not supported.

**Screenshots**
<img width="459" alt="Analysis Error" src="https://github.com/fabric8-analytics/fabric8-analytics-vscode-extension/assets/272218/8a9ba247-7348-4d3a-a1ee-026dc2987253">

**VSCode(please complete the following information):**
 - OS: macOS M2
 - VSCode version: 1.85.1 (Universal)
 - Dependency Analytics Version: v0.7.3
 - NodeJS: v20.10.0

**Additional context**
I'm using pnpm, I'm not testing this on npm since this extension seems not maintained.

**Comment by IlonaShishov** [comment]
Hi @CallMeLaNN ,
Yes, this project has recently undergone major changes and updates and its support has been renewed.
Also our plugin does provide support for npm ecosystem.
The automated Component Analysis error message you are encountering warns you that there is an issue with the package @asrojs/svelte@^4.0.4, its worth taking a look at the package and why its causing an issue in your project.
Assuming the notification will be silenced,  you would not be aware of the issue and the cause with this package.

**Comment by CallMeLaNN** [comment]
It can be any packages, that is one of the warnings. The mentioned package is there and it's annoyed when it warn unnecessarily when node_modules changed in a split second triggered at the time like I mentioned above. So nothing wrong in my dependencies, node_modules and I can run it successfully.

**Comment by IlonaShishov** [comment]
Hmm I understand,
To better assist you, could you confirm that switching from using `pnpm` to using `npm` to install packages gives you any issues? 
Additionally, as a potential solution, would you consider specifying the path to `pnpm` in the `redHatDependencyAnalytics.npm.executable.path` extension workspace setting? if `pnpm` is has a similar API to `npm` it might resolve your issue.

**Comment by meiyingqishi** [comment]
I encountered the same issue and resolved it following @CallMeLaNN's suggestion.
