### ISSUE TITLE
[BUG] request to https://exhort.stage.devshift.net/api/v4/analysis failed, reason: self signed certificate in certificate chain

### ISSUE THREAD

**Issue by balld** [fabric8-analytics/fabric8-analytics-vscode-extension#671]
**Describe the bug**
Using this extension in VS Code on PC behind a corporate firewall with a simple Spring Boot java application I receive this error notification

> request to https://exhort.stage.devshift.net/api/v4/analysis failed, reason: self signed certificate in certificate chain

Our proxy's certificate is added to the OS's trust chain (works fine for Chromium-based browsers etc).

I have installed VS Code win-ca extension which resolves firewall certificate problems for some VS Code features and extensions.
For other Java-based VS Code extensions I am providing path to a custom cacerts file that also includes the proxy cert.

I can't find any documentation or solution as to how I can avoid this problem for Red Hat Dependency Analytics.

**To Reproduce**
1. In VS Code with Red Hat Dependency Analytics installed
2. Opened a simple Maven Java Spring Boot project
3. Waited for project to open
4. Got the error notification above

**Expected behavior**
The extension just accepts the proxy certificate because it is in the OS trust chain, or provides some mechanism for me to configure the proxy cert as trusted.

**VSCode(please complete the following information):**
 - OS: Windows 10
 - VSCode version 1.85.1
 - Dependency Analytics Version 0.9.0

**Additional context**
I am trying to avoid using VS Code settings such as `"http.proxyStrictSSL": false` , but for the purpose of testing I did try that option and the extension still generates the same error.

**Comment by zvigrinberg** [comment]
@balld 
Can you try defining environment variable in your machine  ( user level or global level , it's doesn't matter , as long as it's effective and defined in Vscode process) NODE_TLS_REJECT_UNAUTHORIZED=0, please advise if that worked for you.

**Comment by narsenico** [comment]
I have similar error on my machine (win 11)

> request to https://rhda.rhcloud.com/api/v4/analysis failed, reason: unable to get local issuer certificate

solved settings NODE_TLS_REJECT_UNAUTHORIZED=0 before launching vscode

**Comment by IlonaShishov** [comment]
@balld 
please confirm that the solution suggested by @zvigrinberg has resolved the issue you have reported.

**Comment by tommai78101** [comment]
> I have similar error on my machine (win 11)
> 
> > request to https://rhda.rhcloud.com/api/v4/analysis failed, reason: unable to get local issuer certificate
> 
> solved settings NODE_TLS_REJECT_UNAUTHORIZED=0 before launching vscode

I have a similar error. 

> invalid json response body at https://rhda.rhcloud.com/api/v4/analysis reason: Unexpected token 'U', "Unable to "... is not valid JSON

Where do you put `NODE_TLS_REJECT_UNAUTHORIZED=0` at? I put it in the System Environment Variables in Windows 11, and I don't see how VS Code can load the variable before relaunching / restarting VS Code.

**Comment by zvigrinberg** [comment]
@tommai78101 if the NODE_TLS_REJECT_UNAUTHORIZED=0 is not effective in vscode process ( you can verify it by running a cmd terminal there and type
```shell
echo %NODE_TLS_REJECT_UNAUTHORIZED%
```
if it's effective, you'll see 0 ,otherwise , you won't see anything.

in case you got blank result, try invoking from command prompt using
```shell
set NODE_TLS_REJECT_UNAUTHORIZED=0
c:\path\to\vscode
```

**Comment by IlonaShishov** [comment]
closing issue due to no further messages or continuation of the conversation on this issue.
