### ISSUE TITLE
Private GitHub Registry Support

### ISSUE THREAD

**Issue by JustinVoitel** [fabric8-analytics/fabric8-analytics-vscode-extension#680]
In our projects we use the GitHub Package Registry to import private npm and maven packages. 

When opening a package.json the extension tries to install the package from the npm registry (e.g https://registry.npmjs.org/@my-org/my-package) where it cannot find it so a warning gets printed:
```
Command failed: npm i --package-lock-only --prefix /var/folders/jk/6zn90sz9411ddfhrs9dvxsnc0000gn/T/exhort_xTKVRM npm ERR! code E404 npm ERR! 404 Not Found - GET https://registry.npmjs.org/@my-org%2fmy-package - Not found npm ERR! 404 npm ERR! 404 '@my-org/my-package@1.1.4' is not in this registry. npm ERR! 404 npm ERR! 404 Note that you can also install from a npm ERR! 404 tarball, folder, http url, or git url. npm ERR! A complete log of this run can be found in: /Users/user/.npm/_logs/2024-02-02T09_36_03_371Z-debug-0.log
```

Is there a way to tell the extension to use the registry that is configured via the projects .npmrc ?

**Comment by IlonaShishov** [comment]
Hello,

This issue has been resolved in the latest release, version 0.9.5. We appreciate your help in improving the project. If you have any further issues or suggestions, please feel free to reach out.

Best regards.
