### ISSUE TITLE
stack report generation starts from beginning when user navigates away and then revert back.

### ISSUE THREAD

**Issue by dev-gaur** [fabric8-analytics/fabric8-analytics-vscode-extension#69]
While using VS code extension, stack report generation starts from beginning when I move away from the stack-report tab to some other tab and then revert back to the stack report tab. Lack of caching?

**Comment by invincibleJai** [comment]
thanks @dev-gaur , possibly duplicate of https://github.com/fabric8-analytics/fabric8-analytics-vscode-extension/issues/56
