### ISSUE TITLE
[BUG] invalid json response body at https://rhda.rhcloud.com/api/v4/analysis

### ISSUE THREAD

**Issue by kevchu3** [fabric8-analytics/fabric8-analytics-vscode-extension#693]
**Describe the bug**
I receive the following error when using the VSCode Dependency Analytics extension against my `pom.xml` file:
```
invalid json response body at https://rhda.rhcloud.com/api/v4/analysis reason: Unexpected token 'U', "Unable to "... is not valid JSON
```

**To Reproduce**
1. I have git cloned this repository and opened it in VSCode:
https://github.com/redhat-scholars/tekton-tutorial-greeter

2. When I navigate to this [`pom.xml`](https://github.com/redhat-scholars/tekton-tutorial-greeter/blob/master/springboot/pom.xml) file, I receive the error above.

**Expected behavior**
Dependency Analytics should be able to analyze the `pom.xml` file without throwing an error.

**Screenshots**
![image](https://github.com/fabric8-analytics/fabric8-analytics-vscode-extension/assets/48225327/69008366-44a5-4cc6-b104-ee46cbd6162d)

**Logs**
If applicable, attach logs.

**VSCode(please complete the following information):**
 - OS: Fedora 39
 - VSCode version 1.87.2
 - Dependency Analytics Version v0.9.3
 - Apache Maven 3.9.1 (Red Hat 3.9.1-3)

**Additional context**
I noticed when I attempted to navigate to the URL via HTTPS, it threw an HTTP 404 error.  However, navigating to that same URL via HTTP returned an HTTP 302:
```
$ curl https://rhda.rhcloud.com/api/v4/analysis -I
HTTP/1.1 404 Not Found
set-cookie: 4736dead361c8b7c792d36498d46887b=2f8e092dc86c139b1a7661957620a800; path=/; HttpOnly; Secure; SameSite=None
$ curl http://rhda.rhcloud.com/api/v4/analysis -I
HTTP/1.1 302 Found
content-length: 0
location: https://rhda.rhcloud.com/api/v4/analysis
cache-control: no-cache
```

**Comment by maxandersen** [comment]
this keeps popping up - repeatedly. Can it be fixed or should I just turn it off?

**Comment by IlonaShishov** [comment]
Thank you for reaching out regarding this issue.
Our team has resolved the issue, a patch version will be available soon.

**Comment by SihaoLyu** [comment]
@IlonaShishov The error still pops out on May 23. The latest version is still v0.9.4. Will there be any newer version to fix that?

**Comment by CassandraCat** [comment]
this issue still occurs today
