### ISSUE TITLE
[BUG] rhda.rhcloud.com certificate expired

### ISSUE THREAD

**Issue by yasargil** [fabric8-analytics/fabric8-analytics-vscode-extension#698]
It seems that the certificate for the domain rhda.rhcloud.com expired yesterday:

![Bildschirmfoto 2024-04-03 um 10 02 31](https://github.com/fabric8-analytics/fabric8-analytics-vscode-extension/assets/7766525/40962a15-2a7e-4c55-8260-491edc937db7)
![Bildschirmfoto 2024-04-03 um 10 02 17](https://github.com/fabric8-analytics/fabric8-analytics-vscode-extension/assets/7766525/2b8d551d-7c77-42d1-8ab0-f1d38494cba6)

**Comment by IlonaShishov** [comment]
Thank you @yasargil  for reaching out,
the issue has been fixed,
happy coding.
