### ISSUE TITLE
Lack of padding in some text label containers

### ISSUE THREAD

**Issue by dev-gaur** [fabric8-analytics/fabric8-analytics-vscode-extension#70]
![screenshot from 2018-01-18 15-00-20](https://user-images.githubusercontent.com/7551036/35090695-6e91aa8c-fc60-11e7-9f52-896b08bee009.png)

For an instance, There's no padding/gapping between label and value  in  "Companion Components" area inside Insights card.

**Comment by jyasveer** [comment]
fixed
