### ISSUE TITLE
[BUG] Update vscode-redhat-telemetry to 0.8.0

### ISSUE THREAD

**Issue by fbricon** [fabric8-analytics/fabric8-analytics-vscode-extension#714]
**Describe the bug**
We need to update the vscode-redhat-telemetry package to 0.8.0, so the extension only reports 1  daily startup event

I would have created the PR but I can't because of #713

**Comment by IlonaShishov** [comment]
Thank you @fbricon,
The update will be included in the next release

**Comment by fbricon** [comment]
https://github.com/fabric8-analytics/fabric8-analytics-vscode-extension/blob/master/package.json#L277 is still not updated to 0.8.0
