### ISSUE TITLE
401 error right after authentication

### ISSUE THREAD

**Issue by gorkem** [fabric8-analytics/fabric8-analytics-vscode-extension#85]
I have encountered the following error dialog when I finished the authentication

https://chat.openshift.io/developers/channels/7bckqkca4byqtbrcqhiem4ifze__irzktxnmk7g1umsrzzd6b9zj5w#

**Comment by invincibleJai** [comment]
@gorkem pls test once, post build

**Comment by gorkem** [comment]
I no longer see the issue.

**Comment by invincibleJai** [comment]
Thanks @gorkem, Closing it.
