### ISSUE TITLE
Switching to report page is slow

### ISSUE THREAD

**Issue by gorkem** [fabric8-analytics/fabric8-analytics-vscode-extension#89]
After opening the report opening another editor tab and coming back to the analytics report is unexpectedly slow. 

![report_switch](https://user-images.githubusercontent.com/82738/35244111-16665a30-ff8d-11e7-9771-bb8fe965f0f1.gif)

**Comment by fbricon** [comment]
I confirm the issue

**Comment by fbricon** [comment]
report should probably be saved locally, under the target folder

**Comment by fbricon** [comment]
coming back to the report is much faster now, but still noticeably slow, still takes about 2-3s to load

**Comment by invincibleJai** [comment]
This would be handled as part of next release, with migration to webview

**Comment by invincibleJai** [comment]
closing as fixed
