### ISSUE TITLE
Please rename the Language Server Example

### ISSUE THREAD

**Issue by fbricon** [fabric8-analytics/fabric8-analytics-vscode-extension#90]
See the output folder:
<img width="713" alt="screen shot 2018-01-22 at 3 58 46 pm" src="https://user-images.githubusercontent.com/148698/35244147-30f88454-ff8d-11e7-9dd3-f1e5d0c3b25b.png">

**Comment by invincibleJai** [comment]
This PR should handle it https://github.com/fabric8-analytics/fabric8-analytics-vscode-extension/pull/92
