### ISSUE TITLE
Language server should ignore generated poms

### ISSUE THREAD

**Issue by gorkem** [fabric8-analytics/fabric8-analytics-vscode-extension#91]
Language server reports issues on the `target/stackinfo/poms/pom.xml` even though I have not opened that file. I think the generating the report for the workspace actually causes LSP to be invoked for the generated effective pom. IMHO generated files should be ignored.

**Comment by invincibleJai** [comment]
@gorkem Yes , want to get the content of a document identified by a URI from VS Code ` vscode.workspace.openTextDocument` ,  but without opening it and and it triggers onDidOpen events which invokes lsp. 

https://github.com/Microsoft/vscode/issues/15723

**Comment by invincibleJai** [comment]
this PR fixes it https://github.com/fabric8-analytics/fabric8-analytics-vscode-extension/pull/97 , moved away from VSCode API :)
